"""Curated roles for India's highest-volume fresher and entry-level job categories.
Rows: (type, level, question, how to answer)
"""

ROLES = {
    "Customer Support (BPO)": [
        ("behavioral", "easy", "Why do you want to work in customer support?", "Say you like solving problems and talking to people. Mention patience and clear speaking. Avoid saying 'just for a job'."),
        ("technical", "easy", "What is the difference between a voice process and a non-voice (chat or email) process?", "Voice: live calls, accent and tone matter. Non-voice: typing speed, grammar, multitasking chats. Say which you prefer and why."),
        ("scenario", "medium", "A customer is shouting at you about a wrong bill. What do you do?", "Stay calm, let them finish, apologize for the trouble, take ownership, check the bill, offer a fix, confirm they are satisfied."),
        ("scenario", "medium", "You do not know the answer to a customer's question. What now?", "Be honest, say you will check, use the knowledge base or ask a senior, never guess, update the customer in time."),
        ("technical", "medium", "How do you handle a call when the customer cannot understand your accent or speaks a different language?", "Slow down, simple words, confirm understanding, offer to transfer to a language-matched agent."),
        ("behavioral", "medium", "Are you comfortable with night shifts, rotational shifts and targets?", "Be honest. Show you understand AHT, CSAT and quality scores, and how you will stay healthy and consistent."),
        ("technical", "medium", "What do AHT, CSAT and FCR mean?", "Average handle time, customer satisfaction, first contact resolution. Say balance speed and quality."),
        ("scenario", "hard", "A customer asks for a refund your policy does not allow. How do you respond?", "Empathize, explain the policy simply, offer the best allowed option, escalate if needed, never promise what you cannot give."),
    ],
    "Sales / Business Development Executive": [
        ("behavioral", "easy", "Tell me about yourself and why sales?", "Short story, show energy and target mindset, link any college or part-time selling experience."),
        ("technical", "easy", "What is the difference between a lead, a prospect and a customer?", "Lead: possible interest. Prospect: qualified and fits. Customer: bought. Mention qualifying with budget, need and timeline."),
        ("technical", "medium", "How do you cold call or message a new lead?", "Research first, short opener, ask questions, give value, clear next step. Give a sample opening line."),
        ("scenario", "medium", "A customer says 'your price is too high'. What do you say?", "Do not drop price first. Find the real concern, show value and ROI, compare fairly, offer options."),
        ("scenario", "medium", "You are behind your monthly target with a week left. What do you do?", "Review pipeline, focus on hot leads, follow up, ask for support, stay ethical. Show a plan with numbers."),
        ("technical", "medium", "How do you handle rejection?", "Treat it as data, ask why, improve the pitch, keep your daily call count up."),
        ("technical", "hard", "Sell me this pen (or any product).", "Ask about their need first, then link features to benefits, handle one objection, close with a clear ask."),
        ("behavioral", "medium", "Tell me about a time you convinced someone to agree with you.", "STAR. Show listening first, then a clear result."),
    ],
    "Digital Marketing Executive": [
        ("technical", "easy", "What are the main channels of digital marketing?", "SEO, SEM or paid ads, social media, email, content, affiliate. Say which you have actually worked on."),
        ("technical", "easy", "What is the difference between SEO and SEM?", "Organic vs paid search. Mention keywords, ranking time, cost."),
        ("technical", "medium", "How do you do keyword research and on-page SEO?", "Tools like Google Keyword Planner or Ubersuggest, intent, title, meta, headings, internal links, speed."),
        ("technical", "medium", "How do you measure a campaign? Which metrics matter?", "CTR, CPC, CPA, conversion rate, ROAS, bounce rate. Link metrics to the business goal."),
        ("technical", "medium", "How would you run a Facebook or Instagram ad campaign for a small business?", "Goal, audience, creative, budget, test variants, track with pixel, optimize weekly."),
        ("technical", "medium", "What is Google Analytics and what do you check daily?", "Traffic sources, user behavior, conversions, goals. Mention GA4."),
        ("scenario", "hard", "Your ads get clicks but no sales. What do you check?", "Landing page, offer, audience, tracking, ad-to-page match, checkout friction. Fix one thing at a time."),
        ("behavioral", "medium", "Tell me about a post or campaign you managed and its result.", "Use real numbers even from a college or personal project: reach, leads, growth."),
    ],
    "HR Executive": [
        ("behavioral", "easy", "Why do you want a career in HR?", "People interest, helping both employees and company. Give a real reason, not 'I like people' only."),
        ("technical", "easy", "What are the main functions of HR?", "Recruitment, onboarding, payroll, attendance, employee relations, training, compliance."),
        ("technical", "medium", "Explain the recruitment process from requirement to joining.", "JD, sourcing, screening, interviews, offer, background check, onboarding. Mention drop-off handling."),
        ("technical", "medium", "How do you screen a resume and shortlist candidates?", "Must-have skills, experience fit, stability, communication, red flags. Check with the hiring manager."),
        ("technical", "medium", "What are PF, ESI, gratuity and the basics of a salary slip?", "Basic idea of each in simple words. Say you will always follow the company policy and labour law."),
        ("scenario", "medium", "A selected candidate does not join on the date. What do you do?", "Call, find the reason, offer help, keep a backup candidate, learn for the future."),
        ("scenario", "hard", "Two employees have a serious conflict. How do you handle it?", "Listen to both separately, stay neutral, find facts, follow policy, document, follow up."),
        ("technical", "medium", "Which HR tools or Excel skills do you use?", "ATS, Naukri or LinkedIn, Excel for trackers, basic formulas like VLOOKUP."),
    ],
    "Data Entry / MIS Executive": [
        ("technical", "easy", "What is your typing speed and accuracy?", "Give your real WPM and accuracy percentage and offer to take a test."),
        ("technical", "easy", "What is MIS and why do companies use it?", "Management Information System: reports that help managers decide. Give one example like a daily sales report."),
        ("technical", "medium", "Which Excel functions do you use most?", "VLOOKUP or XLOOKUP, IF, SUMIF, COUNTIF, pivot tables, filters, data validation."),
        ("technical", "medium", "How do you remove duplicates and clean messy data in Excel?", "Remove Duplicates, TRIM, text to columns, conditional formatting, check with COUNTIF."),
        ("technical", "medium", "Explain a pivot table and when you use it.", "Summarize large data quickly by category, then make a simple chart."),
        ("scenario", "medium", "You find an error in data you entered yesterday and the report is already sent. What do you do?", "Tell your lead at once, correct it, resend, add a check so it does not repeat."),
        ("scenario", "hard", "You have 3 reports due today and the data is incomplete. How do you manage?", "Prioritize by deadline, ask for missing data early, deliver what is ready with a clear note."),
        ("behavioral", "medium", "How do you keep data confidential and accurate?", "Double check, follow access rules, never share data, use validation."),
    ],
    "PHP Developer": [
        ("technical", "easy", "What is the difference between echo and print, == and ===?", "Short answers. Then say you use === for strict comparison."),
        ("technical", "easy", "Explain GET vs POST and how sessions and cookies work in PHP.", "Data in URL vs body, session on server, cookie on client, security basics."),
        ("technical", "medium", "How do you prevent SQL injection and XSS in PHP?", "Prepared statements with PDO, escape output, validate input, CSRF tokens."),
        ("technical", "medium", "What is MVC and how does Laravel use it?", "Model, View, Controller. Routes, Eloquent, Blade, migrations. Mention what you built."),
        ("technical", "medium", "Explain joins in MySQL and how you make a query faster.", "Inner and left join, indexes, EXPLAIN, avoid SELECT *."),
        ("technical", "medium", "How do you build and secure a REST API in Laravel?", "Resource controllers, validation, auth with Sanctum or JWT, status codes."),
        ("technical", "hard", "A PHP page takes 8 seconds to load. How do you find the cause?", "Profile queries, N+1, caching, opcache, image size, server logs."),
        ("behavioral", "medium", "Tell me about a project you built in PHP.", "Problem, your part, tools, one challenge, result. Offer a GitHub link."),
    ],
    "Android Developer": [
        ("technical", "easy", "Explain the Android activity lifecycle.", "onCreate, onStart, onResume, onPause, onStop, onDestroy. Say what you do in each."),
        ("technical", "easy", "What is the difference between an Activity and a Fragment?", "Screen vs reusable part of a screen, why fragments help on tablets and navigation."),
        ("technical", "medium", "Kotlin vs Java for Android: why Kotlin?", "Null safety, shorter code, coroutines, official preference."),
        ("technical", "medium", "How do you call an API and show data in a list?", "Retrofit, coroutines, ViewModel, LiveData or StateFlow, RecyclerView or Compose."),
        ("technical", "medium", "What is MVVM and why use it?", "Separate UI and logic, survives rotation, easier testing."),
        ("technical", "medium", "How do you store data locally?", "Room, SharedPreferences or DataStore, when to use each."),
        ("technical", "hard", "Your app crashes on some devices only. How do you debug?", "Crashlytics logs, reproduce on emulator, OS versions, memory, permissions, fix and test."),
        ("behavioral", "medium", "Tell me about an app you built or published.", "Purpose, features, tech, a hard problem solved. Share a Play Store or GitHub link."),
    ],
    "UI/UX Designer": [
        ("technical", "easy", "What is the difference between UI and UX?", "UX is how it works and feels, UI is how it looks. Give a simple example."),
        ("technical", "easy", "Walk me through your design process.", "Research, personas, wireframes, prototype, test, iterate, hand-off."),
        ("technical", "medium", "How do you do user research when you have no budget?", "Talk to 5 users, surveys, competitor review, analytics, usability tests with friends."),
        ("technical", "medium", "Which design tools do you use and how do you hand off to developers?", "Figma, components, auto layout, design system, specs, comments, clear states."),
        ("technical", "medium", "How do you make a design accessible?", "Contrast, font size, touch targets, labels, keyboard use, do not rely on color alone."),
        ("technical", "hard", "Redesign the checkout flow of a shopping app that has high drop-off.", "Find where users drop, reduce steps, guest checkout, trust signals, test the change."),
        ("scenario", "medium", "A developer says your design is hard to build. What do you do?", "Listen, understand the limit, find a simpler version, keep the user goal."),
        ("behavioral", "medium", "Walk me through a project in your portfolio.", "Problem, your role, process, final design, result. Be ready to explain every choice."),
    ],
    "Banking Operations": [
        ("technical", "easy", "What is KYC and why is it required?", "Know Your Customer: identity and address proof, prevents fraud and money laundering, RBI rules."),
        ("technical", "easy", "Explain the difference between savings, current and fixed deposit accounts.", "Purpose, interest, withdrawals, who uses each."),
        ("technical", "medium", "What are NEFT, RTGS, IMPS and UPI?", "Speed, limits and timing in simple words. Say UPI is instant and 24x7."),
        ("technical", "medium", "How does a loan process work: from application to disbursal?", "Application, documents, credit check, approval, sanction, agreement, disbursal."),
        ("technical", "medium", "What is a CIBIL score and why does it matter?", "Credit score range 300 to 900, affects loan approval and rate."),
        ("scenario", "medium", "A customer's transaction failed but money is debited. What do you do?", "Check status, explain reversal timeline, raise a ticket, follow up, keep the customer informed."),
        ("scenario", "hard", "You notice a transaction that looks suspicious. What do you do?", "Do not tip off the customer, follow the process, report to the compliance or AML team, document."),
        ("behavioral", "medium", "How do you stay accurate with cash and numbers under pressure?", "Double check, follow the checklist, reconcile daily, ask when unsure."),
    ],
    "Accountant (Tally)": [
        ("technical", "easy", "What are the golden rules of accounting?", "Personal, real and nominal accounts with the debit and credit rule for each, with one example."),
        ("technical", "easy", "What is the difference between a voucher and a ledger in Tally?", "Voucher records a transaction, ledger shows the account summary."),
        ("technical", "medium", "How do you record a purchase with GST in Tally?", "Create ledgers, purchase voucher, CGST and SGST or IGST, party details, check the entry."),
        ("technical", "medium", "How do you do a bank reconciliation?", "Match the bank statement with the books, list differences like cheques not cleared, prepare the BRS."),
        ("technical", "medium", "What is GST and how do you file GSTR-1 and GSTR-3B?", "Output and input tax, return purpose and due dates, reconcile with books and 2B."),
        ("technical", "medium", "What is TDS and where do you deduct it?", "Tax deducted at source, common sections, rates, deposit and return, Form 16A."),
        ("technical", "hard", "Your trial balance does not tally. How do you find the error?", "Check totals, transposition errors, one-sided entries, suspense, review recent entries."),
        ("scenario", "medium", "Month-end is tomorrow and some invoices are missing. What do you do?", "List the missing items, follow up now, book provisions if policy allows, tell your manager."),
    ],
}

ALIASES = {
    "Customer Support (BPO)": ["bpo", "customer support", "customer service", "call center", "call centre", "voice process", "non voice", "non-voice", "chat support", "customer care", "helpdesk", "help desk"],
    "Sales / Business Development Executive": ["sales", "business development", "bde", "telecaller", "tele caller", "inside sales", "relationship manager", "lead generation"],
    "Digital Marketing Executive": ["digital marketing", "seo", "social media", "performance marketing", "content marketing", "marketing executive", "ppc"],
    "HR Executive": ["human resource", "hr executive", "hr recruiter", "hr generalist", "talent acquisition", "hr manager", "hr intern"],
    "Data Entry / MIS Executive": ["data entry", "mis executive", "mis ", "back office", "backoffice", "back-office", "operator"],
    "PHP Developer": ["php", "laravel", "codeigniter", "wordpress", "mysql developer"],
    "Android Developer": ["android", "kotlin", "mobile developer", "mobile app", "flutter", "react native"],
    "UI/UX Designer": ["ui/ux", "ui ux", "ux designer", "ui designer", "figma", "graphic designer", "product designer", "user experience"],
    "Banking Operations": ["banking", "bank ", "kyc", "loan", "branch operations", "credit analyst", "fintech operations", "bfsi"],
    "Accountant (Tally)": ["accountant", "tally", "accounts executive", "bookkeep", "gst", "finance executive", "accounts payable", "accounts receivable"],
}
