"""Curated question banks by role, plus AI-generated company-specific questions.

The curated bank works offline and instantly. Company questions are generated by the fast
Nemotron model, cached in memory, and fall back to the curated set if the model fails.
"""
import threading

from app import llm, market, singleflight
from app import bank_in, bank_us

# (type, level, question, how to answer)
_B = {
    "QA Automation Engineer": [
        ("technical", "easy", "What is the difference between smoke, sanity and regression testing?", "Define each in one line, then say when you run it in your pipeline."),
        ("technical", "easy", "How do you decide which test cases to automate?", "Repeatable, stable, high-risk, data-heavy flows first. Mention ROI and maintenance cost."),
        ("technical", "medium", "How do you handle flaky tests in Selenium or Playwright?", "Explicit waits, stable locators, test isolation, retries only as a last step, quarantine and root-cause."),
        ("technical", "medium", "Explain the Page Object Model and why you use it.", "Separate locators and actions from tests. Give one real example and the maintenance benefit."),
        ("technical", "medium", "How do you test REST APIs? What do you assert besides status code?", "Schema, headers, response time, negative cases, auth, idempotency. Name your tool (Postman, RestAssured)."),
        ("technical", "hard", "Design an automation framework from scratch for a new web product.", "Language and tool choice, structure, reporting, CI, test data, parallel runs, how you would scale it."),
        ("technical", "hard", "How do you run automation in CI/CD and decide when a build is blocked?", "Quality gates, test levels per stage, flaky policy, reports, who gets notified."),
        ("behavioral", "medium", "Tell me about a critical bug you found late. What did you change after?", "STAR format. End with a process change, not just the fix."),
        ("scenario", "medium", "Developers say your failing test is a test problem, not a bug. What do you do?", "Reproduce, share evidence, pair on it, stay factual and calm."),
        ("scenario", "hard", "The release is tomorrow and 15% of regression is failing. What is your call?", "Triage by risk, separate real bugs from flakiness, give a clear go/no-go with data."),
    ],
    "Java Developer": [
        ("technical", "easy", "What is the difference between an interface and an abstract class in Java?", "Multiple inheritance of type, default methods, state. Give when you pick each."),
        ("technical", "easy", "Explain the difference between == and equals(), and why hashCode matters.", "Reference vs value equality, the contract, HashMap behavior."),
        ("technical", "medium", "How does HashMap work internally? What changed in Java 8?", "Buckets, hashing, collisions, treeification, resize, thread-safety."),
        ("technical", "medium", "Explain how Spring Boot auto-configuration and dependency injection work.", "Component scan, conditional beans, starters, constructor injection."),
        ("technical", "medium", "What are the differences between synchronized, volatile and ReentrantLock?", "Visibility vs atomicity, fairness, when each is enough."),
        ("technical", "hard", "How would you find and fix a memory leak in a production Java service?", "Heap dump, GC logs, profilers, typical causes (static maps, listeners, thread locals)."),
        ("technical", "hard", "Design a REST service that handles 5,000 requests per second.", "Stateless design, caching, DB pooling, async, rate limits, observability."),
        ("behavioral", "medium", "Describe a time you improved the performance of an application.", "Measure before and after with numbers."),
        ("scenario", "medium", "A production API is returning 500 errors after a deployment. Walk me through your first 15 minutes.", "Check rollback option, logs, metrics, recent change, communicate status."),
        ("scenario", "hard", "A client wants a feature that will hurt system design. How do you respond?", "Understand the real need, present trade-offs, offer an alternative, document the decision."),
    ],
    "Python Developer": [
        ("technical", "easy", "What is the difference between a list, tuple, set and dict?", "Mutability, ordering, lookup cost, a typical use for each."),
        ("technical", "easy", "Explain decorators and generators with a use case.", "Wrapping behavior, lazy iteration, a real example from your work."),
        ("technical", "medium", "What is the GIL and how does it affect concurrency?", "CPU-bound vs I/O-bound, threads vs processes vs asyncio."),
        ("technical", "medium", "How do you structure a FastAPI or Django project for a team?", "Layers, settings, dependency injection, tests, migrations."),
        ("technical", "medium", "How do you write testable Python code? What do you mock and what not?", "pytest, fixtures, mock external boundaries only."),
        ("technical", "hard", "A Python service uses too much memory. How do you diagnose it?", "tracemalloc, profilers, generators, chunking, leak patterns."),
        ("technical", "hard", "Design a background job system with retries and idempotency.", "Queue, workers, retry with backoff, dedupe keys, dead-letter handling."),
        ("behavioral", "medium", "Tell me about a bug that took you a long time to find.", "STAR. Show your debugging method."),
        ("scenario", "medium", "Your script processes a 10 GB file and crashes. What do you change?", "Stream, chunk, avoid loading all in memory, checkpoint."),
        ("scenario", "hard", "You inherit an untested legacy codebase and must add a feature in a week.", "Characterization tests around the change, small safe steps, communicate risk."),
    ],
    "Business Analyst": [
        ("technical", "easy", "What is the difference between functional and non-functional requirements?", "Give two examples of each from a real project."),
        ("technical", "easy", "What artifacts do you create in a project, and when?", "BRD, user stories, process flows, wireframes, traceability matrix."),
        ("technical", "medium", "How do you write good user stories and acceptance criteria?", "INVEST, Given-When-Then, a concrete example."),
        ("technical", "medium", "How do you prioritize requirements when everything is urgent?", "MoSCoW, value vs effort, stakeholder alignment, trade-off conversation."),
        ("technical", "medium", "How do you validate requirements with stakeholders?", "Walkthroughs, prototypes, sign-off, change control."),
        ("technical", "hard", "Walk me through how you would map an as-is to to-be process for onboarding.", "Interviews, current flow, pain points, gaps, target flow, KPIs."),
        ("behavioral", "medium", "Tell me about a time stakeholders disagreed on requirements.", "STAR. Focus on how you facilitated the decision."),
        ("scenario", "medium", "Scope creep is hitting the sprint. What do you do?", "Impact analysis, change request, product owner decision, document it."),
        ("scenario", "hard", "A client changes a core requirement two days before UAT.", "Assess impact, options with cost and date, get written approval."),
        ("technical", "medium", "What SQL or data skills do you use as a BA?", "Joins, filters, validating reports, finding data gaps."),
    ],
    "Data Analyst": [
        ("technical", "easy", "What is the difference between INNER, LEFT and FULL joins?", "One-line definitions and which rows each keeps."),
        ("technical", "easy", "How do you clean a messy dataset?", "Missing values, duplicates, types, outliers, documenting every step."),
        ("technical", "medium", "Write or explain a query for the second highest salary per department.", "Window functions (DENSE_RANK) vs subquery; mention ties."),
        ("technical", "medium", "How do you choose the right chart for a business question?", "Match chart to question, avoid clutter, one key message."),
        ("technical", "medium", "A KPI dropped 20% this week. How do you investigate?", "Check data quality first, segment by dimension, time, release, external events."),
        ("technical", "hard", "How would you design an A/B test and read the result?", "Hypothesis, metric, sample size, duration, significance vs practical impact."),
        ("behavioral", "medium", "Tell me about an analysis that changed a business decision.", "STAR with the number that mattered."),
        ("scenario", "medium", "A manager asks for a dashboard by tomorrow with unclear requirements.", "Ask 3 key questions, ship a small version, iterate."),
        ("scenario", "hard", "Two reports show different revenue numbers. What do you do?", "Definitions, filters, sources, reconcile, document the single source of truth."),
        ("technical", "medium", "Which tools have you used (Excel, SQL, Power BI, Tableau, Python) and for what?", "Be specific about one project per tool."),
    ],
    "DevOps Engineer": [
        ("technical", "easy", "What is CI/CD and what does your pipeline look like?", "Stages: build, test, scan, deploy, with a real tool example."),
        ("technical", "easy", "Explain containers vs virtual machines.", "Isolation level, startup, resource use, when each fits."),
        ("technical", "medium", "How do you manage infrastructure as code with Terraform?", "State, modules, environments, plan/apply review, drift."),
        ("technical", "medium", "How do you do zero-downtime deployments in Kubernetes?", "Rolling update, readiness probes, blue-green or canary, rollback."),
        ("technical", "medium", "How do you monitor a production system?", "Metrics, logs, traces, SLOs, useful alerts vs noise."),
        ("technical", "hard", "A pod is in CrashLoopBackOff. Walk me through debugging.", "describe, logs (previous), events, config, probes, resources."),
        ("technical", "hard", "Design a secure CI/CD pipeline.", "Secrets handling, least privilege, image scanning, signed artifacts, approvals."),
        ("behavioral", "medium", "Tell me about an outage you handled.", "STAR: timeline, fix, postmortem, prevention."),
        ("scenario", "medium", "Deployment frequency is low because releases are scary. What do you do?", "Smaller changes, automated tests, feature flags, safe rollback."),
        ("scenario", "hard", "Cloud costs doubled this month. How do you find out why?", "Cost explorer, tags, top services, idle resources, ownership."),
    ],
    "Frontend Developer": [
        ("technical", "easy", "Explain the difference between let, const and var, and hoisting.", "Scope, reassignment, temporal dead zone."),
        ("technical", "easy", "What is the box model and how do flexbox and grid differ?", "One-dimensional vs two-dimensional layout with a use case each."),
        ("technical", "medium", "How does the React rendering cycle work? When do you use useMemo or useCallback?", "State change, reconciliation, avoid premature optimization, measure first."),
        ("technical", "medium", "How do you improve page load performance?", "Bundle size, lazy loading, images, caching, Core Web Vitals."),
        ("technical", "medium", "How do you make a web app accessible?", "Semantic HTML, keyboard, ARIA only when needed, contrast, screen reader testing."),
        ("technical", "hard", "Design the frontend of a real-time dashboard with large data.", "State management, virtualization, websockets, throttling, error states."),
        ("behavioral", "medium", "Tell me about a UI bug that was hard to reproduce.", "STAR, show your method."),
        ("scenario", "medium", "The designer's mock cannot be built as drawn. What do you do?", "Explain constraint, offer closest option, agree quickly."),
        ("scenario", "hard", "Users report the app is slow only on mobile. How do you investigate?", "Real-device profiling, network throttling, long tasks, images, JS cost."),
        ("technical", "medium", "How do you test frontend code?", "Unit, component, e2e, what you mock, one real example."),
    ],
    "Project Manager": [
        ("technical", "easy", "How do you plan a project and track progress?", "Scope, WBS, milestones, risks, a status cadence and tool."),
        ("technical", "easy", "Agile vs waterfall: when do you use which?", "Requirement stability, feedback needs, team and client context."),
        ("technical", "medium", "How do you manage risks?", "Risk register, probability and impact, owners, mitigation, reviews."),
        ("technical", "medium", "How do you handle a client who keeps changing scope?", "Change control, impact on time and cost, written approval."),
        ("technical", "medium", "Which metrics do you report to stakeholders?", "Velocity or burn-up, budget, risks, quality, blockers, forecast."),
        ("technical", "hard", "A project is 30% behind schedule. What are your options?", "Root cause, re-baseline, scope cut, resources, honest client conversation."),
        ("behavioral", "medium", "Tell me about a conflict in your team and how you resolved it.", "STAR with the outcome and what you learned."),
        ("scenario", "medium", "Your key developer resigns mid-sprint.", "Knowledge transfer, re-plan, inform stakeholders, backfill."),
        ("scenario", "hard", "Two senior stakeholders give you conflicting priorities.", "Bring them together, use business value, get one decision owner."),
        ("behavioral", "medium", "How do you manage offshore and onshore teams across time zones?", "Overlap hours, clear handoffs, written updates, ownership."),
    ],
    "Data Engineer": [
        ("technical", "easy", "What is the difference between ETL and ELT?", "Where transformation happens and why modern warehouses favor ELT."),
        ("technical", "easy", "What is partitioning and why does it matter?", "Prune data scans, choose key by access pattern."),
        ("technical", "medium", "How do you design an idempotent pipeline?", "Deterministic keys, upserts, replay safely, checkpointing."),
        ("technical", "medium", "Batch vs streaming: how do you choose?", "Latency need, cost, complexity, a concrete example."),
        ("technical", "medium", "How do you ensure data quality?", "Tests, schema checks, freshness, anomaly alerts, ownership."),
        ("technical", "hard", "A Spark job is slow. How do you tune it?", "Skew, shuffles, partitions, broadcast joins, caching, file sizes."),
        ("technical", "hard", "Design a pipeline that ingests 1 TB per day from many sources.", "Ingestion, landing zone, schema evolution, orchestration, monitoring, cost."),
        ("behavioral", "medium", "Tell me about a pipeline failure that impacted business users.", "STAR with prevention steps."),
        ("scenario", "medium", "An upstream team changes a schema without notice.", "Detect, contract tests, quarantine, talk to owner, versioning."),
        ("scenario", "hard", "The finance report is wrong and the CFO is waiting.", "Triage the lineage, communicate early, fix and prevent."),
    ],
}

_B.update(bank_us.ROLES)
_B.update(bank_in.ROLES)

GENERAL = [
    ("behavioral", "easy", "Tell me about yourself.", "Present, past, future in about 90 seconds, tied to this role."),
    ("behavioral", "easy", "Why do you want this role and this company?", "Two specific reasons about the work, not only salary."),
    ("behavioral", "medium", "What is your biggest strength and a weakness you are fixing?", "Real weakness plus concrete steps and progress."),
    ("behavioral", "medium", "Tell me about a time you failed.", "Own it, show the lesson and what you changed."),
    ("behavioral", "medium", "Describe a conflict with a colleague or manager.", "STAR, stay professional, focus on resolution."),
    ("scenario", "medium", "How do you handle tight deadlines and many priorities?", "A method plus an example with the result."),
    ("scenario", "hard", "Where do you see yourself in five years?", "Growth tied to the role, honest and realistic."),
]

_ALIASES = {
    "QA Automation Engineer": ["qa", "test", "sdet", "quality", "selenium", "automation"],
    "Java Developer": ["java", "spring", "backend", "back-end", "j2ee"],
    "Python Developer": ["python", "django", "flask", "fastapi"],
    "Business Analyst": ["business analyst", "ba ", "product owner", "requirements", "systems analyst"],
    "Data Analyst": ["data analyst", "analytics", "bi ", "power bi", "tableau", "reporting"],
    "DevOps Engineer": ["devops", "sre", "kubernetes", "infrastructure", "platform engineer"],
    "Frontend Developer": ["frontend", "front-end", "front end", "react", "angular", "ui developer", "javascript", "web developer"],
    "Project Manager": ["project manager", "program manager", "scrum", "delivery manager", "pmo"],
    "Data Engineer": ["data engineer", "etl", "spark", "big data", "pipeline", "warehouse"],
}

_ALIASES.update(bank_us.ALIASES)
_ALIASES.update(bank_in.ALIASES)


def roles() -> list[str]:
    return list(_B)


def match_role(text: str) -> str | None:
    t = (text or "").lower().strip() + " "
    if not t.strip():
        return None
    for name in _B:
        if name.lower() == t.strip():
            return name
    best, score = None, 0
    for name, keys in _ALIASES.items():
        s = sum(1 for k in keys if k in t)
        if s > score:
            best, score = name, s
    return best


def _fmt(rows):
    return [{"type": t, "level": lv, "question": q, "hint": h} for t, lv, q, h in rows]


def curated(role_text: str) -> dict:
    name = match_role(role_text)
    rows = list(_B[name]) if name else []
    rows += GENERAL
    return {"role": name or "General", "matched": name is not None, "questions": _fmt(rows)}


# ---------- company-specific (AI) ----------
COMPANY_SYSTEM = """You are an interview coach who knows how {company} interviews candidates. {market}
For the role "{role}" at {company}, write exactly 8 likely interview questions that reflect that company's known
style (values, typical rounds, product domain). Mix technical, behavioral and scenario questions, easy to hard.
If you are not sure how {company} interviews, say so in "note" and give strong generic questions for the role.
Do not invent confidential or leaked questions. Return ONLY JSON:
{{"note": str (one sentence about their interview style or your uncertainty),
 "questions": [{{"type": "technical|behavioral|scenario", "level": "easy|medium|hard", "question": str, "hint": str (one short line on how to answer)}}]}}"""

_cache: dict[tuple, dict] = {}
_cache_lock = threading.Lock()
_MAX_CACHE = 300


def _clean(s: str, n: int) -> str:
    return " ".join((s or "").split())[:n]


def _company_questions_uncached(company: str, role: str, country: str) -> dict:
    company, role = _clean(company, 80), _clean(role, 120) or "this role"
    key = (company.lower(), role.lower(), market.normalize(country))
    with _cache_lock:
        if key in _cache:
            return _cache[key]
    out = llm.chat_json(
        "company_bank",
        COMPANY_SYSTEM.format(company=company, role=role, market=market.context(country)),
        f"Company: {company}\nRole: {role}",
        model=llm.FAST_MODEL,
    )
    qs = []
    for q in out.get("questions", [])[:10]:
        if not isinstance(q, dict) or not q.get("question"):
            continue
        qs.append(
            {
                "type": q.get("type") if q.get("type") in ("technical", "behavioral", "scenario") else "technical",
                "level": q.get("level") if q.get("level") in ("easy", "medium", "hard") else "medium",
                "question": _clean(str(q["question"]), 500),
                "hint": _clean(str(q.get("hint", "")), 300),
            }
        )
    if not qs:
        raise llm.LLMError("no company questions returned")
    res = {"company": company, "note": _clean(str(out.get("note", "")), 300), "questions": qs}
    with _cache_lock:
        if len(_cache) >= _MAX_CACHE:
            _cache.clear()
        _cache[key] = res
    return res


def company_questions(company: str, role: str, country: str) -> dict:
    """Same company, role and country at the same moment share one AI call."""
    k = (_clean(company, 80).lower(), (_clean(role, 120) or "this role").lower(), market.normalize(country))
    with singleflight.lock(("bank",) + k):
        return _company_questions_uncached(company, role, country)
