"""Extra curated roles based on what the US IT staffing and contract market hires for most.

Sources checked: Robert Half 2026 tech hiring data (AI/ML, security, cloud, IT operations), Procom 2026 US
salary guide (AI engineering, cybersecurity, DevOps, ML, cloud, .NET, big data, SAP, Workday) and Hays
2026 contractor demand (data, enterprise platforms such as Salesforce, SAP, ServiceNow).
Rows: (type, level, question, how to answer)
"""

ROLES = {
    ".NET Developer": [
        ("technical", "easy", "What is the difference between .NET Framework, .NET Core and modern .NET?", "Cross-platform, performance, side-by-side versions, say which you use and why you migrated."),
        ("technical", "easy", "Explain value types vs reference types and boxing in C#.", "Stack vs heap in simple terms, boxing cost, a case where it hurt performance."),
        ("technical", "medium", "How do async and await work, and what goes wrong with .Result or .Wait()?", "State machine, no thread blocked, deadlock in sync contexts, ConfigureAwait."),
        ("technical", "medium", "Explain dependency injection lifetimes: transient, scoped, singleton.", "One example each, and the captive dependency bug."),
        ("technical", "medium", "Entity Framework: how do you avoid N+1 queries and slow queries?", "Include/projection, AsNoTracking, indexes, look at the generated SQL."),
        ("technical", "hard", "Design a Web API for orders with auth, versioning and high load.", "JWT or OAuth, versioning, pagination, caching, rate limits, health checks, logging."),
        ("technical", "hard", "How do you find a memory or CPU problem in a production ASP.NET service?", "Counters, dotnet-dump or profiler, GC behavior, common leaks like event handlers."),
        ("scenario", "medium", "A client wants to move a legacy .NET Framework app to the cloud. How do you plan it?", "Assess, strangler approach, upgrade path, tests first, containers or App Service, risks."),
    ],
    "Full Stack Developer": [
        ("technical", "easy", "Walk me through what happens from typing a URL to seeing the page.", "DNS, TCP/TLS, request, server, response, render. Show you know both sides."),
        ("technical", "medium", "REST vs GraphQL: when do you pick each?", "Over-fetching, caching, tooling, team skills, a real example."),
        ("technical", "medium", "How do you handle authentication and sessions in a SPA with an API?", "Token vs cookie, httpOnly, refresh, CSRF and XSS tradeoffs."),
        ("technical", "medium", "How do you design a database schema and API for a new feature?", "Entities, relations, indexes, migrations, versioning, validation."),
        ("technical", "medium", "How do you keep a React or Angular app fast?", "Code splitting, memoization, lazy loading, bundle size, measuring with Lighthouse."),
        ("technical", "hard", "Design a real-time notifications feature end to end.", "WebSockets or SSE, queue, persistence, scale-out, retries, offline users."),
        ("behavioral", "medium", "Tell me about a feature you shipped across front end and back end.", "STAR. Show you owned the whole slice and measured the result."),
        ("scenario", "hard", "The page is slow in production but fast locally. How do you debug it?", "Network tab, API timings, DB queries, payload size, caching, CDN, then fix the biggest cost."),
    ],
    "Salesforce Developer": [
        ("technical", "easy", "What is the difference between a workflow, Process Builder and Flow, and what do you use now?", "Flow is the current tool, say when Apex is still better."),
        ("technical", "easy", "Explain governor limits and name the ones you hit most.", "SOQL queries, DML, CPU time, heap. Bulkify and avoid queries in loops."),
        ("technical", "medium", "How do you write a bulk-safe Apex trigger?", "One trigger per object, handler class, collections, maps, no SOQL or DML in loops."),
        ("technical", "medium", "Lightning Web Components vs Aura: how do they communicate?", "Properties, events, LMS, wire service, Apex calls. Say you prefer LWC."),
        ("technical", "medium", "Explain the Salesforce security model.", "Org-wide defaults, roles, profiles and permission sets, sharing rules, field-level security."),
        ("technical", "hard", "How would you integrate Salesforce with an external ERP?", "REST or platform events, named credentials, async Apex, retries, error logging, idempotency."),
        ("technical", "hard", "How do you deploy and test changes across sandboxes?", "SFDX or DevOps Center, Git, CI, test classes with 75% coverage but meaningful asserts."),
        ("scenario", "medium", "A nightly batch job fails halfway with record lock errors. What do you do?", "Logs, batch size, ordering, retries, lock causes, make it re-runnable."),
    ],
    "ServiceNow Developer": [
        ("technical", "easy", "What are the core ServiceNow tables and how does the CMDB fit in?", "Task, incident, change, CI tables, relationships, keeping CMDB data trusted."),
        ("technical", "easy", "Business rule vs client script vs UI policy vs flow: when do you use each?", "Server vs client, timing (before, after, async), prefer no-code Flow when possible."),
        ("technical", "medium", "How do you build a catalog item with approvals and fulfillment?", "Variables, variable sets, workflow or Flow Designer, approvals, tasks, testing."),
        ("technical", "medium", "How do you integrate ServiceNow with another system?", "REST messages, Integration Hub, MID server, import sets, transform maps, error handling."),
        ("technical", "medium", "How do ACLs work and how do you debug one?", "Table, field, role, condition, script; security debugger."),
        ("technical", "hard", "How do you move and control changes between instances?", "Update sets vs app repository and source control, scoped apps, testing, back-out plan."),
        ("technical", "hard", "A form is slow to load. How do you find out why?", "Transaction logs, client scripts, business rules, onLoad scripts, related lists."),
        ("scenario", "medium", "The business asks for heavy customization. How do you respond?", "Out-of-the-box first, upgrade cost, configuration over code, document the decision."),
    ],
    "AWS Cloud Engineer": [
        ("technical", "easy", "Explain IAM users, roles and policies, and least privilege.", "Roles over keys, scoped policies, MFA, one real example."),
        ("technical", "easy", "What is the difference between EC2, ECS, EKS and Lambda?", "Control vs convenience, cost model, when each fits."),
        ("technical", "medium", "How do you design a VPC with public and private subnets?", "CIDR plan, NAT, route tables, security groups vs NACLs, endpoints."),
        ("technical", "medium", "How do you build highly available and fault tolerant systems on AWS?", "Multi-AZ, auto scaling, load balancer, health checks, backups, RTO and RPO."),
        ("technical", "medium", "How do you manage infrastructure as code?", "Terraform or CloudFormation, state, modules, review and CI, drift detection."),
        ("technical", "hard", "Your AWS bill doubled this month. What do you do?", "Cost Explorer, tags, find top services, rightsizing, savings plans, guardrails and alerts."),
        ("technical", "hard", "Design a secure multi-account setup for an enterprise.", "Organizations, SCPs, landing zone, central logging, network hub, break-glass access."),
        ("scenario", "hard", "An S3 bucket was found public. What are your first steps?", "Block access, assess exposure with logs, rotate secrets, report, add preventive controls."),
    ],
    "Cybersecurity Analyst": [
        ("technical", "easy", "Explain the CIA triad and give a real example of each.", "Confidentiality, integrity, availability with simple incidents."),
        ("technical", "easy", "What is the difference between a vulnerability, a threat and a risk?", "Define and link them: risk = likelihood x impact."),
        ("technical", "medium", "Walk me through how you would triage a phishing alert.", "Headers, URLs, sandbox, affected users, block, reset, report, lessons."),
        ("technical", "medium", "What is the MITRE ATT&CK framework and how do you use it?", "Map detections to tactics, find gaps, threat hunting."),
        ("technical", "medium", "How do you use a SIEM such as Splunk or Sentinel day to day?", "Correlation rules, tuning false positives, dashboards, investigations."),
        ("technical", "hard", "Describe the incident response lifecycle with a real or example incident.", "Prepare, detect, contain, eradicate, recover, lessons learned. Stay calm and structured."),
        ("technical", "hard", "How do you prioritize 5,000 vulnerabilities from a scan?", "Exploitability, asset criticality, exposure, compensating controls, SLAs."),
        ("scenario", "hard", "You see data leaving the network at 3 AM to an unknown IP. What now?", "Confirm, isolate host, preserve evidence, escalate, scope the damage, communicate."),
    ],
    "Scrum Master": [
        ("technical", "easy", "What are the Scrum events, roles and artifacts?", "Name them briefly and the purpose of each."),
        ("technical", "medium", "How do you run a retrospective that produces real change?", "Format variety, one or two actions with owners, follow up next sprint."),
        ("technical", "medium", "The team keeps missing sprint goals. What do you look at?", "Estimation, interruptions, dependencies, WIP, data from velocity and burndown."),
        ("technical", "medium", "How do you coach a Product Owner who changes priorities mid-sprint?", "Protect the sprint, explain cost of change, backlog refinement, agree a rule."),
        ("technical", "hard", "How do you scale Agile across several teams and dependencies?", "Scrum of Scrums, SAFe or LeSS basics, program increments, shared board, risk."),
        ("behavioral", "medium", "Tell me about a conflict in a team and how you handled it.", "STAR. A servant leader facilitates, does not dictate."),
        ("scenario", "medium", "Management wants the team to commit to more than it can deliver.", "Use data, show trade-offs, protect the team, offer options."),
        ("scenario", "hard", "A distributed team across US and India time zones loses focus. What do you change?", "Overlap hours, async updates, clear working agreements, rotate meeting times."),
    ],
    "Network Engineer": [
        ("technical", "easy", "Explain the OSI model and where common devices and protocols sit.", "Layers 1 to 7 with real examples: switch L2, router L3, TCP L4."),
        ("technical", "easy", "What is the difference between TCP and UDP, and when do you use each?", "Reliability vs speed, examples like web vs voice."),
        ("technical", "medium", "How do OSPF and BGP differ, and where do you use each?", "IGP vs EGP, metrics, convergence, typical designs."),
        ("technical", "medium", "Explain VLANs, trunking and spanning tree.", "Segmentation, tagging, loop prevention, a troubleshooting story."),
        ("technical", "medium", "How do you troubleshoot a site that cannot reach the internet?", "Layer by layer: link, IP, gateway, DNS, firewall, ISP. Name your tools."),
        ("technical", "hard", "Design a network for two offices and a data center with redundancy.", "Dual links, SD-WAN or MPLS, VPN, HSRP or VRRP, segmentation, monitoring."),
        ("technical", "hard", "How do firewalls, NAT and VPNs fit in a secure design?", "Zones, policies, site-to-site and remote access, logging."),
        ("scenario", "hard", "A core switch fails at 2 PM on a business day.", "Fail over, communicate, restore, root cause, post-incident review."),
    ],
    "Machine Learning Engineer": [
        ("technical", "easy", "What is overfitting and how do you prevent it?", "Train vs validation gap, regularization, more data, cross-validation, simpler model."),
        ("technical", "medium", "How do you choose evaluation metrics for an imbalanced classification problem?", "Precision, recall, F1, PR-AUC over accuracy, business cost of errors."),
        ("technical", "medium", "How do you take a model from notebook to production?", "Packaging, API, versioning, CI/CD, monitoring, rollback."),
        ("technical", "medium", "How do you detect and handle data drift and model decay?", "Monitor inputs and outputs, thresholds, retraining triggers, shadow runs."),
        ("technical", "medium", "How do you build an LLM or RAG application and keep answers reliable?", "Chunking, embeddings, retrieval quality, prompts, evals, guardrails, cost and latency."),
        ("technical", "hard", "Design a real-time recommendation system.", "Candidate generation, ranking, features, latency budget, feedback loop, A/B tests."),
        ("technical", "hard", "How do you reduce inference cost and latency?", "Batching, quantization, distillation, caching, smaller model routing."),
        ("scenario", "medium", "The model is accurate offline but the business sees no gain. What now?", "Check the metric, data mismatch, UX, run an A/B test, align with the stakeholder."),
    ],
    "Data Scientist": [
        ("technical", "easy", "Explain bias vs variance.", "Underfit vs overfit with a simple example and how you balance them."),
        ("technical", "medium", "How do you design and read an A/B test?", "Hypothesis, sample size, randomization, p-value and effect size, pitfalls like peeking."),
        ("technical", "medium", "How do you handle missing data and outliers?", "Understand why it is missing, impute or drop, robust methods, document choices."),
        ("technical", "medium", "Explain a model you built end to end and how you chose it.", "Problem, data, baseline, features, validation, result in business terms."),
        ("technical", "medium", "Write or describe SQL to find the top customers by month with a running total.", "Window functions, group by, careful date handling."),
        ("technical", "hard", "How would you predict customer churn?", "Define churn, features, leakage, model, metrics, how the business acts on it."),
        ("behavioral", "medium", "Tell me about a time your analysis changed a business decision.", "STAR. Lead with the decision and the number."),
        ("scenario", "medium", "A stakeholder does not trust your model. How do you win them over?", "Explainability, simple baseline, show errors honestly, involve them early."),
    ],
    "SAP Consultant": [
        ("technical", "easy", "What are the main SAP modules and how do they integrate?", "FI, CO, MM, SD, PP, HCM and the S/4HANA view. Pick your module and show the links."),
        ("technical", "easy", "What is the difference between ECC and S/4HANA?", "In-memory HANA, simplified data model, Fiori, migration approaches."),
        ("technical", "medium", "Walk me through a procure-to-pay or order-to-cash flow in SAP.", "Documents and postings at each step, where it hits finance."),
        ("technical", "medium", "How do you gather requirements and do fit-gap analysis?", "Workshops, standard first, gaps, RICEFW list, sign-off."),
        ("technical", "medium", "How do you plan data migration and testing for a go-live?", "Cleansing, mock loads, reconciliation, UAT, cutover plan, hypercare."),
        ("technical", "hard", "A month-end close fails because of a posting error. How do you handle it?", "Find the document, root cause, correct with proper reversal, inform finance, prevent a repeat."),
        ("behavioral", "medium", "Tell me about an implementation you supported and your role.", "STAR. Be clear on your module, team size, outcome."),
        ("scenario", "medium", "Users resist a new SAP process. What do you do?", "Training, champions, show benefit, support after go-live."),
    ],
}

ALIASES = {
    ".NET Developer": [".net", "dotnet", "c#", "asp.net", "csharp", "entity framework"],
    "Full Stack Developer": ["full stack", "fullstack", "full-stack", "mern", "mean stack", "node", "software engineer"],
    "Salesforce Developer": ["salesforce", "apex", "lwc", "sfdc", "lightning"],
    "ServiceNow Developer": ["servicenow", "service now", "snow", "itsm", "cmdb"],
    "AWS Cloud Engineer": ["aws", "azure", "gcp", "cloud", "cloud architect", "solutions architect", "terraform"],
    "Cybersecurity Analyst": ["security", "cyber", "soc analyst", "infosec", "penetration", "siem", "grc"],
    "Scrum Master": ["scrum master", "agile coach", "agile", "safe "],
    "Network Engineer": ["network", "cisco", "ccna", "routing", "firewall", "wan", "voip"],
    "Machine Learning Engineer": ["machine learning", "ml engineer", "ai engineer", "mlops", "llm", "deep learning", "genai", "nlp"],
    "Data Scientist": ["data scientist", "data science", "statistician", "predictive"],
    "SAP Consultant": ["sap", "s/4hana", "abap", "fico", "workday", "oracle erp"],
}
