"""Basic-level India interview content (10th/12th/graduate): his question set plus drafted gap fillers.
Generated from reviewed drafts. Fields: id, cat, q, ref (sample answer or guidance), tip, hi (Hindi hint), t (type), lv (level), iv (used in mock interviews)."""

DATA = [{'id': 'A1',
  'cat': 'general',
  'q': 'Tell me about yourself.',
  'ref': 'My name is [your name]. I am from [your city]. I have completed my [10th / 12th / graduation] in [your stream]. I learn quickly '
         'and I am a good listener. I want to start my career in [this role] and grow with your company.',
  'tip': 'Use 4-5 short sentences: name, city, studies, one skill, why you want this job. Speak slowly and clearly.',
  'hi': 'Naam, shehar, padhai, ek skill aur is job ki wajah bataiye. Dheere aur saaf boliye.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A2',
  'cat': 'general',
  'q': 'What are your strengths?',
  'ref': 'My greatest strength is my ability to learn things quickly. or "I think my greatest strength is my positive attitude, even in '
         'the hardest times."',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A3',
  'cat': 'general',
  'q': 'What are your weaknesses?',
  'ref': 'I care too much about my work. or "I feel restless until my work is done."',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A4',
  'cat': 'general',
  'q': 'What is your short-term goal?',
  'ref': "My short-term goal is to fulfil my parents' dreams.",
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A5',
  'cat': 'general',
  'q': 'What is your long-term',
  'ref': 'My long-term goal is to become a respectable and successful person.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A6',
  'cat': 'general',
  'q': 'Why do you want this job?',
  'ref': 'I believe this job will build my confidence and improve my skills. I would love to grow with your company.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True,
  'why': True},
 {'id': 'A7',
  'cat': 'general',
  'q': 'Why should we hire you?',
  'ref': 'Sir, I am a self-motivated person. As a fresher, I need a platform to use my knowledge. If you give me a chance, I will give my '
         'best for your company.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A8',
  'cat': 'general',
  'q': 'Why do you want to join us and not go for higher studies?',
  'ref': 'I believe this job will build my confidence and improve my skills. I would love to grow with your company. I am not leaving my '
         'studies. I will continue my studies along with work.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A9',
  'cat': 'general',
  'q': 'What do you know about our company?',
  'ref': 'Sir, your company is well known for customer service, and you also have a great relationship with your customers.',
  'tip': 'Visit the company website the day before and replace this sample with real facts: what the company does, one service or client, '
         'and where the office is.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A10',
  'cat': 'bpo',
  'q': 'What do you know about the call centre industry?',
  'ref': 'A call centre is a service desk where the customer associate handles a large volume of calls to provide services to the client.',
  'tip': '',
  'hi': '',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'A11',
  'cat': 'bpo',
  'q': 'What are the types of call centres? What is the difference?',
  'ref': "Inbound: the associate receives calls about customers' queries or needs. Example: a customer calls a telecom company to ask "
         'about the current internet tariff. Outbound: the associate makes calls to customers for business or sales. Example: a bank calls '
         'to offer a personal loan.',
  'tip': '',
  'hi': '',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'A12',
  'cat': 'bpo',
  'q': 'What is the difference between BPO and a call centre?',
  'ref': 'A BPO (Business Process Outsourcing) organisation performs a process, or part of a process, for another business. Outsourcing is '
         "done to save cost or gain productivity. A call centre performs the part of a client's business that involves handling telephone "
         'calls, for example customer complaints. So a call centre can be considered a BPO.',
  'tip': '',
  'hi': '',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'A13',
  'cat': 'bpo',
  'q': 'What is an international BPO?',
  'ref': 'An international BPO serves customers outside India, for example in the US or UK. The work is often in night shifts because of '
         'their time zone. A call centre is one kind of BPO that handles customer calls.',
  'tip': 'Say it in your own words. Mention that you are ready for shifts.',
  'hi': '',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'A14',
  'cat': 'bpo',
  'q': 'What is a call centre job according to you?',
  'ref': 'A call centre job means talking to customers, understanding their problem and helping them with the right solution.',
  'tip': 'The interviewer is checking whether you know the job. Talk about helping customers with their problems.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A15',
  'cat': 'bpo',
  'q': 'What do you understand by "customer satisfaction"?',
  'ref': "Any business depends on the quality of service offered to the customer. To do this, you need to understand the customer's needs "
         'and problems, think from their point of view and try to meet their demands. This is customer satisfaction.',
  'tip': '',
  'hi': '',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'A16',
  'cat': 'bpo',
  'q': 'What will you do if a customer abuses you on the phone?',
  'ref': "First, I will stay calm, listen to the customer's problem and try to understand what made them annoyed. Next, I will politely "
         'ask them to calm down. Then I will assure them that I will solve their problem. Last, I will find the root cause of the problem, '
         "fix it and make sure it does not happen again. Learning from the mistake can also improve the company's process and policy.",
  'tip': '',
  'hi': '',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'A17',
  'cat': 'bpo',
  'q': 'What qualities should a customer associate have to be a perfect customer associate?',
  'ref': 'Good listening skills, problem-solving, concentration and patience.',
  'tip': '',
  'hi': '',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'A18',
  'cat': 'bpo',
  'q': 'How do you handle work pressure?',
  'ref': 'To handle a pressure situation, I keep my focus on work and avoid frustration. or "I have worked under pressure a lot during my '
         'college days. I have realised that I actually work well under pressure. The pressure brings out maximum efficiency in me."',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A19',
  'cat': 'bpo',
  'q': 'What is your typing skill?',
  'ref': 'My typing speed is around [your speed] words per minute with good accuracy. If you do not know your speed, say: I am good at '
         'typing and I practise regularly.',
  'tip': 'Give your real number from a typing test. This is a quick-check question, so be honest.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A20',
  'cat': 'bpo',
  'q': 'Can you handle multiple calls at the same time?',
  'ref': 'If you have experience, describe it. If you do not, say: once training is provided, I can handle multiple calls with ease.',
  'tip': 'Never claim experience you do not have.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A21',
  'cat': 'bpo',
  'q': 'How do you rate yourself on communication skills?',
  'ref': 'I rate my communication skills around 8 out of 10. I am improving every day by speaking and listening in English.',
  'tip': 'Call centres look for good communication, so rate yourself high but honestly, and mention how you improve.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A22',
  'cat': 'bpo',
  'q': 'What is the key to success in a call centre?',
  'ref': 'A call centre is all about providing quality service to the customer. If you handle customers well and offer good service, you '
         'can be successful in a call centre.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A23',
  'cat': 'bpo',
  'q': 'What procedure do you follow while talking to a customer?',
  'ref': '1. Greet the customer. 2. Introduce yourself. 3. Ask how you can help. 4. Listen patiently. 5. Give the best possible solution. '
         '6. Cross-check that the customer is satisfied. 7. Ask if they need any further help.',
  'tip': '',
  'hi': '',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'A24',
  'cat': 'bpo',
  'q': 'Do you like multi-tasking, or do you prefer to handle one problem at a time?',
  'ref': 'Depending on the situation, I can multi-task or handle one problem at a time. But multi-tasking has the upper hand because it '
         'increases efficiency in a call centre.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A25',
  'cat': 'bpo',
  'q': 'What if the customer is not happy with your answer or solution?',
  'ref': 'If the customer is not happy with my answer or solution, I will ask them to hold the line and pass the call to a manager or team '
         'leader.',
  'tip': '',
  'hi': '',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'A26',
  'cat': 'bpo',
  'q': 'What will be your approach to improve customer service?',
  'ref': 'For better customer service, I would take feedback from the customer and ask how we can improve in solving their problem and '
         'give them good service.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A27',
  'cat': 'bpo',
  'q': 'How do you deal with a difficult customer?',
  'ref': 'Listen actively. Rephrase their concerns. Give a workable solution. Take action and follow up. Fix the problem immediately. Use '
         'the feedback. Reduce unpleasant situations by doing proper research and preparation.',
  'tip': '',
  'hi': '',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'A28',
  'cat': 'bpo',
  'q': 'How do you measure good customer service?',
  'ref': 'Number of repeat customers. Number and type of complaints. Number of referrals from current customers. Sales figures, if the '
         'service is product based. Customer satisfaction surveys. Benchmarking against competitors. Rate of new customers enrolling. '
         'Number of returns.',
  'tip': '',
  'hi': '',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'A29',
  'cat': 'bpo',
  'q': 'What steps will you take to deal with an unsatisfied customer?',
  'ref': 'Apologise and offer a better option. Act quickly and resolve the complaint. Take responsibility for what made the customer '
         'unhappy. Compensate with a better deal or free service.',
  'tip': '',
  'hi': '',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'A30',
  'cat': 'bpo',
  'q': "How can you resolve the problem to the customer's satisfaction?",
  'ref': 'Talk to the customer (a phone call is often quicker and more personal than a standard email or letter). Find out the problem and '
         'the requirement by listening carefully. Ask about wider issues with open questions, such as "Are you happy with our service or '
         'product?" Offer something back, such as an offer, discount or coupon, if there is a real issue and a chance of losing the '
         'customer. Confirm your solution with a follow-up email or letter to avoid disputes. Follow up regularly, and ask a team member '
         'to check that all is well.',
  'tip': '',
  'hi': '',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'A31',
  'cat': 'bpo',
  'q': 'What is a back-end process?',
  'ref': 'Back office: the part of the company with employees doing administrative and support work. They do not deal directly with '
         'customers but are the backbone of the company. Example: in a bank or finance company, managing and settling accounts, clearing '
         'payments, updating records, running IT infrastructure, data entry and HR. The back office does not generate revenue, but the '
         'front-office sales team cannot complete a deal without its support. Front office: people who deal directly with customers, such '
         'as sales and customer support. They generate revenue. Back-office staff work behind the scenes, execute the deals sales brings '
         'in and take them to completion. Both offices must work hand in hand.',
  'tip': '',
  'hi': '',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'A32',
  'cat': 'general',
  'q': 'Are you willing to work night shifts or weekends?',
  'ref': 'No, I do not have any problem with night shifts. Yes, I am willing to work on weekends.',
  'tip': 'Answer in a full sentence and be honest. If you have a limit, say it politely before joining.',
  'hi': 'Poora sentence mein jawab do. Sach boliye.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A33',
  'cat': 'general',
  'q': 'Are you comfortable working in a team?',
  'ref': 'Yes, I am comfortable working in a team. I can also work independently without supervision.',
  'tip': 'Add one short example from school, college or home.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A34',
  'cat': 'general',
  'q': 'Are you willing to work long hours if the project demands it?',
  'ref': 'Yes, I am willing to work long hours when the project demands it.',
  'tip': 'Answer in a full sentence. Be honest about your limits.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A35',
  'cat': 'general',
  'q': 'Are you willing to relocate or travel?',
  'ref': 'I would definitely consider it. If the opportunity is appropriate, rewarding and feasible, I do not think I will have any issue '
         'with relocation or travel.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A36',
  'cat': 'general',
  'q': 'Where do you see yourself in 3 years? In 5 years?',
  'ref': 'My current goal is to find a career position that ensures continued growth and new challenges every day. Three years from now, I '
         'see myself as an experienced and reliable senior member of the team. Five years from now, I expect to be ready for managerial '
         'responsibilities. I want a stable career in a single organisation, and I hope to get that wherever I start.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A37',
  'cat': 'general',
  'q': 'How long will you work for us after we hire you?',
  'ref': 'I am a fresher, and nothing is better for me than starting my professional career in a reputed company like yours. If everything '
         'goes well, I look forward to a long stay here, as long as the company needs me.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A38',
  'cat': 'general',
  'q': 'Do you have any questions for us?',
  'ref': 'Can I know about my role in detail?',
  'tip': 'Never say "no". Ask about your role, the training or the shift timings.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A39',
  'cat': 'general',
  'q': 'How well do you handle change?',
  'ref': 'I try to stay focused on who I am and what I need. This helps me respond to change effectively. or (his longer answer): "Of '
         'course I can handle change. In my previous company, one of the bosses left. The new boss completely changed our strategy and '
         'project timings, and I was flexible and hard-working enough to manage it."',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A40',
  'cat': 'general',
  'q': 'How quickly do you adapt to new technology?',
  'ref': 'I adapt quickly to new situations. I am clear about my job role and mentally prepared for challenges, so I can learn fast and '
         'apply my new knowledge. In my student life, I had to clear new papers and projects every semester and I enjoyed it. I will enjoy '
         'picking up new technologies in my professional life too.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A41',
  'cat': 'general',
  'q': 'How do you make important decisions?',
  'ref': 'I believe decisions should be made with all the information. If you miss an important detail, it is easy to make a bad decision. '
         'So I make important decisions after getting all the information.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A42',
  'cat': 'general',
  'q': 'Are you an organised person?',
  'ref': 'Yes, I am quite organised. I keep all my documents, certificates and files labelled and sorted, so I can find anything in '
         'seconds. I also keep my computer desktop clean.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A43',
  'cat': 'general',
  'q': 'Are you reliable? Can I trust you with responsibilities?',
  'ref': 'Yes, I am not only reliable but also very dependable. If a task is assigned to me, it will be handled properly and completed '
         'within the deadline.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A44',
  'cat': 'general',
  'q': 'What are the three most important things for you in a job?',
  'ref': 'Honesty, loyalty and determination to achieve my team\'s target. or "Professionalism, growth and a healthy work-life balance."',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A45',
  'cat': 'general',
  'q': 'What motivates you?',
  'ref': 'My biggest motivation is my family. They are my biggest source of inspiration and my strongest supporters. When I see my parents '
         'working, it gives me the drive to be like them. Their dedication motivates me.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A46',
  'cat': 'general',
  'q': 'What makes you happy?',
  'ref': 'Success makes me happy. I also feel happy after completing my tasks and achieving my goals. Holidays with my family also make me '
         'happy.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A47',
  'cat': 'general',
  'q': 'What makes you angry?',
  'ref': 'I get angry when I am falsely accused of something I did not do. Lack of order and discipline also irritates me, but I have '
         'learned to cope and adjust with other people.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A48',
  'cat': 'general',
  'q': 'If you could change one thing about your personality, what would it be?',
  'ref': 'I get easily frustrated with people who do not work hard. But I know people have different work styles and habits. So if I could '
         'change something, I would like to be more understanding.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A49',
  'cat': 'general',
  'q': 'Are you open to taking risks? Do you like experimenting?',
  'ref': 'It is always good to venture into new areas and new technologies. I am an adaptive person and my diligence helps me pick up new '
         'things quickly. Taking risks can give good or bad results, but the exercise itself is a great learning experience. Such '
         'experiences create experts, and I want to become a subject matter expert (SME) someday.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A50',
  'cat': 'general',
  'q': 'On a scale of 1 to 10, how would you rate yourself as a leader?',
  'ref': 'I rate my leadership skills 8 out of 10. There is much to learn, but I have always taken the lead. For example, [your example '
         'from school, college, sports, NCC or a group project].',
  'tip': 'Use one real example of leading a group. Do not copy someone else story.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A51',
  'cat': 'general',
  'q': 'If you won a Rs 10 crore lottery, would you still work?',
  'ref': 'Yes, I would still work to build my career. With the lottery money, I will buy a big house for my mom and dad.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A52',
  'cat': 'general',
  'q': 'What is more important to you: money or success?',
  'ref': 'Success is most important to me, because money follows success. For example, players, singers and runners earn money wherever '
         'they succeed.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A53',
  'cat': 'general',
  'q': 'What is more important to you: work or money?',
  'ref': 'Both work and money are important to me, but if I must choose one, I choose work. If the work is good, the money will grow '
         'automatically.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A54',
  'cat': 'general',
  'q': 'What is smart work and what is hard work?',
  'ref': 'Smart work means planning well and finishing the task efficiently in less time. Hard work means putting in more time and effort. '
         'I believe both are needed: I plan smartly and then work hard to complete the task properly.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A55',
  'cat': 'general',
  'q': 'Discuss your five characteristics.',
  'ref': '1. Independent. 2. Responsible. 3. Hard-working. 4. Multi-tasker. 5. Good learner.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A56',
  'cat': 'general',
  'q': 'Tell us about your hobbies.',
  'ref': 'Browsing the internet. Listening to music. Chatting with friends. Reading newspapers. Reading books. Shopping. Watching movies.',
  'tip': '',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'A57',
  'cat': 'general',
  'q': 'What is your most memorable day / happiest moment so far?',
  'ref': '',
  'tip': 'Use your own real story. Say what happened, how you felt and what you learned. Keep it positive.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'A58',
  'cat': 'general',
  'q': 'Which movie did you see last? Tell me something about it.',
  'ref': '',
  'tip': 'Use your own real story. Say what happened, how you felt and what you learned. Keep it positive.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'B1',
  'cat': 'general',
  'q': 'Say something about your family.',
  'ref': 'My family is a small family with [number] members. My father is a [occupation] and takes good care of our family. My mother is a '
         '[occupation]. We are a small family, but we always spend good time together.',
  'tip': 'Replace the [brackets] with your own details. Keep it to 4-5 simple sentences.',
  'hi': '[Brackets] mein apni jaankari daaliye. 4-5 aasaan sentences.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'B2',
  'cat': 'general',
  'q': 'Say something about your mother.',
  'ref': 'My mother is [name]. She is a [occupation]. She always took good care of me. We have a very close connection, and I love her '
         'very much.',
  'tip': 'Replace the [brackets] with your own details. Keep it to 4-5 simple sentences.',
  'hi': '[Brackets] mein apni jaankari daaliye. 4-5 aasaan sentences.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'B3',
  'cat': 'general',
  'q': 'Say something about your father.',
  'ref': 'My father is [name]. He is a [occupation]. He is a simple and caring man. He cares about our family very much, and I love him '
         'very much.',
  'tip': 'Replace the [brackets] with your own details. Keep it to 4-5 simple sentences.',
  'hi': '[Brackets] mein apni jaankari daaliye. 4-5 aasaan sentences.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'B4',
  'cat': 'general',
  'q': 'Say something about your hometown.',
  'ref': '[Your town] is a [small town / city] in [your state]. It is a simple place where a person can live comfortably. We get '
         'education, markets, banks, a hospital and other facilities here, so it is a very suitable place to live.',
  'tip': 'Replace the [brackets] with your own details. Keep it to 4-5 simple sentences.',
  'hi': '[Brackets] mein apni jaankari daaliye. 4-5 aasaan sentences.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'B5',
  'cat': 'general',
  'q': 'Say something about your city.',
  'ref': '[Your city] is a [metro city] in [your state]. Many companies, shopping malls, showrooms and universities are here. It is a very '
         'good city.',
  'tip': 'Replace the [brackets] with your own details. Keep it to 4-5 simple sentences.',
  'hi': '[Brackets] mein apni jaankari daaliye. 4-5 aasaan sentences.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'B6',
  'cat': 'general',
  'q': 'Compare your hometown and your city.',
  'ref': '[Your hometown] is a small place, and [your city] is a big city. We get many things in the city that we cannot get in the town, '
         'like shopping malls, hospitals with the best equipment and many universities.',
  'tip': 'Replace the [brackets] with your own details. Keep it to 4-5 simple sentences.',
  'hi': '[Brackets] mein apni jaankari daaliye. 4-5 aasaan sentences.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'C1',
  'cat': 'bpo',
  'q': 'What is the difference between a voice process and a non-voice process?',
  'ref': '',
  'tip': 'Voice = talking on calls. Non-voice = chat, email, data entry. Say which you prefer and why.',
  'hi': 'Voice = call par baat. Non-voice = chat/email/typing. Apni pasand wajah ke saath.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'C2',
  'cat': 'bpo',
  'q': 'The customer does not understand your English. What will you do?',
  'ref': '',
  'tip': 'Speak slower, use simple words, repeat, and confirm. Ask if they prefer Hindi, if the process allows it.',
  'hi': 'Dheere bolo, aasaan shabd, dohrao. Process allow kare to Hindi mein poochho.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'C3',
  'cat': 'bpo',
  'q': "You do not know the answer to a customer's question. What do you do?",
  'ref': '',
  'tip': 'Do not guess. Say "Let me check this for you", use the knowledge base or ask your team lead, then call back if needed.',
  'hi': 'Andaza mat lagao. "Let me check" boliye, guide dekho ya team lead se poochho.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'C4',
  'cat': 'bpo',
  'q': 'What is AHT (average handling time) and why does it matter?',
  'ref': '',
  'tip': 'Average time you spend on one call. Companies track it, but quality comes first. Balance speed with correct answers.',
  'hi': 'Ek call par lagne wala average time. Speed ke saath sahi jawab bhi zaroori.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'C5',
  'cat': 'bpo',
  'q': 'Tell me about a time you helped someone solve a problem.',
  'ref': '',
  'tip': 'A simple story: the problem, what you did, the result. A school or family example is fine.',
  'hi': 'Chhoti kahani: problem, aapne kya kiya, natija.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'C6',
  'cat': 'bpo',
  'q': 'What salary do you expect?',
  'ref': '',
  'tip': 'As a fresher, say you would like to follow company standards for freshers and you care more about learning. Know the market '
         'range before.',
  'hi': '"Company ke fresher standard ke hisaab se, mujhe seekhna zyada zaroori hai."',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'C7',
  'cat': 'bpo',
  'q': 'Can you travel to the office daily?',
  'ref': '',
  'tip': 'Be honest about distance and timing. If cab or transport is offered, say you will use it.',
  'hi': 'Doori aur time sach batao. Cab ho to bolo.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'C8',
  'cat': 'bpo',
  'q': 'Can you stay focused on repetitive work?',
  'ref': '',
  'tip': 'Say you can stay focused, use small goals, and take short breaks. Pride in accuracy.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'D1',
  'cat': 'dataentry',
  'q': 'Tell me about yourself.',
  'ref': 'I have 4 years of experience in data entry, where I was responsible for entering, updating and maintaining accurate records in '
         'systems such as MS Excel and company databases. I am detail-oriented, fast at typing and careful about accuracy. Over the years, '
         'I have learned to handle large volumes of data under tight deadlines while keeping accuracy high. Now I am looking to join a '
         'company where I can continue to grow and take on more responsibility.',
  'tip': 'Change the years and tools to match your own real experience.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'D2',
  'cat': 'dataentry',
  'q': 'What is your typing speed and accuracy?',
  'ref': 'My typing speed is around 55-60 words per minute with an accuracy rate of over 95%. I have taken regular typing tests to '
         'maintain and improve my speed and accuracy.',
  'tip': 'Change the years and tools to match your own real experience.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'D3',
  'cat': 'dataentry',
  'q': 'How do you ensure accuracy in your work?',
  'ref': 'I double-check my work before submission, use built-in tools like spell check or data validation, and follow a checklist. If I '
         'am unsure about any data, I always clarify with my supervisor or the source before continuing.',
  'tip': 'Change the years and tools to match your own real experience.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'D4',
  'cat': 'dataentry',
  'q': 'What software or tools have you used for data entry?',
  'ref': 'I have mainly worked with Microsoft Excel, Google Sheets and company CRM systems. I also have basic experience entering data '
         'into ERP systems and handling scanned documents with OCR software.',
  'tip': 'Change the years and tools to match your own real experience.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'D5',
  'cat': 'dataentry',
  'q': 'How do you handle repetitive work without losing focus?',
  'ref': 'I break my tasks into smaller goals and take short breaks to stay focused. I also use keyboard shortcuts and templates to speed '
         'up repetitive work. I enjoy routine work and take pride in staying consistent.',
  'tip': 'Change the years and tools to match your own real experience.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'D6',
  'cat': 'dataentry',
  'q': 'Describe a time you made a mistake and how you handled it.',
  'ref': 'Once, I noticed that I had entered incorrect invoice data because of a formatting issue. As soon as I caught the mistake, I '
         'informed my supervisor, corrected the records and helped update the report before submission. Since then, I have been extra '
         'careful with formatting and use data validation rules wherever possible.',
  'tip': 'Change the years and tools to match your own real experience.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'D7',
  'cat': 'dataentry',
  'q': 'What are your strengths?',
  'ref': 'My strengths are attention to detail, fast and accurate typing, time management and the ability to stay focused on repetitive '
         'tasks. I also have good communication skills for clarifying data-related issues.',
  'tip': 'Change the years and tools to match your own real experience.',
  'hi': '',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'E1',
  'cat': 'exp',
  'q': 'Why did you leave your last job?',
  'ref': 'I am looking for better growth and more learning opportunities. I am thankful for what I learned at my last company.',
  'tip': 'Never speak badly about a past employer. Talk about growth.',
  'hi': '',
  't': 'behavioral',
  'lv': 'medium',
  'iv': False},
 {'id': 'E2',
  'cat': 'exp',
  'q': 'Tell us about your team mates and your team.',
  'ref': 'I worked well with my team. When there were issues, I spoke openly with my team members and my team leader and focused on '
         'finishing the work properly.',
  'tip': 'Stay positive. Do not complain about colleagues.',
  'hi': '',
  't': 'behavioral',
  'lv': 'medium',
  'iv': False},
 {'id': 'E3',
  'cat': 'exp',
  'q': 'Why is there a gap in your work history?',
  'ref': 'I was feeling exhausted after years of non-stop work, so I decided to take a break and spend time with my family. I am happy to '
         'have returned fully recharged.',
  'tip': 'Be honest, short and positive. Then say you are ready to work.',
  'hi': '',
  't': 'behavioral',
  'lv': 'medium',
  'iv': False},
 {'id': 'E4',
  'cat': 'exp',
  'q': 'Can you tell us something about your previous boss?',
  'ref': 'He was very friendly with me. He inspired me a lot. I have always tried to learn something new from him.',
  'tip': 'Say something positive and what you learned.',
  'hi': '',
  't': 'behavioral',
  'lv': 'medium',
  'iv': False},
 {'id': 'E5',
  'cat': 'exp',
  'q': 'What irritates you about co-workers?',
  'ref': 'I understand that teamwork is important. If someone is not serious about their work or does low-quality work that affects the '
         'whole project, I do not like it. But I try to talk to them politely and help.',
  'tip': 'Pick a work habit, not a person, and end with how you handle it.',
  'hi': '',
  't': 'behavioral',
  'lv': 'medium',
  'iv': False},
 {'id': 'E6',
  'cat': 'exp',
  'q': 'Is there any particular kind of person you cannot work with?',
  'ref': 'No. I can work with all kinds of people. I focus on the work and respect everyone.',
  'tip': 'Do not name types of people. Say you can work with everyone.',
  'hi': '',
  't': 'behavioral',
  'lv': 'medium',
  'iv': False},
 {'id': 'E7',
  'cat': 'exp',
  'q': 'What qualities do you look for in your senior?',
  'ref': 'I look for qualities like intelligence, a good sense of humour and dedication to the team.',
  'tip': 'Pick 2-3 positive qualities, like guidance, fairness and support.',
  'hi': '',
  't': 'behavioral',
  'lv': 'medium',
  'iv': False},
 {'id': 'E8',
  'cat': 'exp',
  'q': 'What are the most important things for you as a manager?',
  'ref': 'Two things are most important for a manager to succeed: my team should be happy and keep performing, and the project I am '
         'working on with my team should finish successfully with minimum problems.',
  'tip': 'Say team first, then results.',
  'hi': '',
  't': 'behavioral',
  'lv': 'medium',
  'iv': False},
 {'id': 'CC1',
  'cat': 'cabin',
  'q': 'Tell me about yourself in English.',
  'ref': 'Guidance: Name, city, studies, one strength (smile, teamwork, languages), why cabin crew. 5 sentences, clear voice, smile.',
  'tip': 'Name, city, studies, one strength (smile, teamwork, languages), why cabin crew. 5 sentences, clear voice, smile.',
  'hi': 'Naam, shehar, padhai, ek khoobi aur cabin crew kyun. Muskurakar saaf bolo.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'CC2',
  'cat': 'cabin',
  'q': 'Why do you want to be cabin crew?',
  'ref': 'Guidance: Mention service to people, travel with responsibility, teamwork and safety. Avoid "I only want to travel and glamour".',
  'tip': 'Mention service to people, travel with responsibility, teamwork and safety. Avoid "I only want to travel and glamour".',
  'hi': 'Logon ki seva, safety, teamwork - sirf ghoomna ya glamour mat boliye.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True,
  'why': True},
 {'id': 'CC3',
  'cat': 'cabin',
  'q': 'Why do you want to join our airline?',
  'ref': 'Guidance: Read about the airline: routes, base cities, service style, fleet. Say one thing you like.',
  'tip': 'Read about the airline: routes, base cities, service style, fleet. Say one thing you like.',
  'hi': 'Airline ke baare mein padho: routes, base city, service. Ek cheez jo pasand hai.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC4',
  'cat': 'cabin',
  'q': 'What are the main duties of cabin crew?',
  'ref': 'Guidance: Safety first (briefing, emergency, doors, seat belts), then service (welcome, meals, comfort), then handling '
         'passengers.',
  'tip': 'Safety first (briefing, emergency, doors, seat belts), then service (welcome, meals, comfort), then handling passengers.',
  'hi': 'Pehle safety (briefing, emergency), phir service (swagat, khana), phir passengers ko sambhalna.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC5',
  'cat': 'cabin',
  'q': 'Which is more important for cabin crew: service or safety?',
  'ref': 'Guidance: Safety. Cabin crew are first of all trained for safety; service comes next. Give a one-line reason.',
  'tip': 'Safety. Cabin crew are first of all trained for safety; service comes next. Give a one-line reason.',
  'hi': 'Safety. Cabin crew sabse pehle safety ke liye hote hain.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC6',
  'cat': 'cabin',
  'q': 'Are you comfortable with height, weight and medical rules for this job?',
  'ref': 'Guidance: Rules vary by airline (minimum height, weight in proportion, vision, no visible tattoos). Say you have read the rules '
         'and fit them. Be honest.',
  'tip': 'Rules vary by airline (minimum height, weight in proportion, vision, no visible tattoos). Say you have read the rules and fit '
         'them. Be honest.',
  'hi': 'Rules airline ke hisaab se badalte hain (height, weight, aankhein). Padhkar sach batao.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC7',
  'cat': 'cabin',
  'q': 'How is your reach? (Arm-reach test)',
  'ref': 'Guidance: Many airlines test if you can reach an overhead bin, often about 210 cm (varies). Say you will do the test and stretch '
         'fully.',
  'tip': 'Many airlines test if you can reach an overhead bin, often about 210 cm (varies). Say you will do the test and stretch fully.',
  'hi': 'Kai airline arm-reach test lete hain (overhead bin tak pahunch). Test mein poora stretch karo.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC8',
  'cat': 'cabin',
  'q': 'Are you comfortable with irregular shifts, nights and being away from home?',
  'ref': 'Guidance: Say yes if true. Mention family support and that you will manage rest and health.',
  'tip': 'Say yes if true. Mention family support and that you will manage rest and health.',
  'hi': 'Raat ki shift, ghar se door rehna - sach boliye, family support batao.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC9',
  'cat': 'cabin',
  'q': 'Can you swim? Are you comfortable with heights and small spaces?',
  'ref': 'Guidance: Some airlines ask. Answer honestly. If you cannot swim, say you will learn in training.',
  'tip': 'Some airlines ask. Answer honestly. If you cannot swim, say you will learn in training.',
  'hi': 'Kuch airline poochhte hain. Sach bolo, na aata ho to training mein seekhne ko bolo.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC10',
  'cat': 'cabin',
  'q': 'A passenger is angry because the meal they ordered is finished. What will you do?',
  'ref': 'Guidance: Apologise, stay calm, offer alternatives, ask a senior crew, thank them for understanding.',
  'tip': 'Apologise, stay calm, offer alternatives, ask a senior crew, thank them for understanding.',
  'hi': 'Sorry bolo, shaant raho, doosra option do, senior crew ko batao.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'CC11',
  'cat': 'cabin',
  'q': 'A passenger refuses to fasten the seat belt or switch off the phone. What will you do?',
  'ref': 'Guidance: Explain it is for their safety and the rules, ask politely twice, then call the senior crew. Do not argue.',
  'tip': 'Explain it is for their safety and the rules, ask politely twice, then call the senior crew. Do not argue.',
  'hi': 'Safety ka reason batao, politely 2 baar kaho, phir senior crew. Bahas nahi.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'CC12',
  'cat': 'cabin',
  'q': 'A passenger feels sick or faints in flight. What will you do?',
  'ref': 'Guidance: Stay calm, check, call senior crew and ask for a doctor on board, use first aid kit/oxygen as trained, tell the '
         'cockpit.',
  'tip': 'Stay calm, check, call senior crew and ask for a doctor on board, use first aid kit/oxygen as trained, tell the cockpit.',
  'hi': 'Shaant raho, senior crew ko batao, doctor ki announcement, first aid, cockpit ko batao.',
  't': 'scenario',
  'lv': 'hard',
  'iv': True},
 {'id': 'CC13',
  'cat': 'cabin',
  'q': 'A child is crying and the parents are stressed. What do you do?',
  'ref': 'Guidance: Speak kindly, offer water/toy/colouring if available, help the parents settle, stay patient.',
  'tip': 'Speak kindly, offer water/toy/colouring if available, help the parents settle, stay patient.',
  'hi': 'Pyaar se baat, paani/khilona do, parents ko comfortable karo.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'CC14',
  'cat': 'cabin',
  'q': 'What is IATA? Do you know any airport codes?',
  'ref': 'Guidance: IATA = International Air Transport Association. Three-letter airport codes: DEL (Delhi), BOM (Mumbai), BLR '
         '(Bengaluru), CCU (Kolkata), HYD (Hyderabad).',
  'tip': 'IATA = International Air Transport Association. Three-letter airport codes: DEL (Delhi), BOM (Mumbai), BLR (Bengaluru), CCU '
         '(Kolkata), HYD (Hyderabad).',
  'hi': 'IATA airline ka international sangathan hai. DEL, BOM, BLR jaise 3-letter codes.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC15',
  'cat': 'cabin',
  'q': 'How do you say the time in 24-hour format? What is 6 PM?',
  'ref': 'Guidance: Airlines use the 24-hour clock. 6 PM = 1800 hours. Practise a few.',
  'tip': 'Airlines use the 24-hour clock. 6 PM = 1800 hours. Practise a few.',
  'hi': 'Airline mein 24-hour clock. Shaam 6 baje = 1800.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC16',
  'cat': 'cabin',
  'q': 'What do you do during a safety demonstration?',
  'ref': 'Guidance: Show seat belt, oxygen mask, life jacket and exits clearly while speaking, facing the passengers.',
  'tip': 'Show seat belt, oxygen mask, life jacket and exits clearly while speaking, facing the passengers.',
  'hi': 'Seat belt, oxygen mask, life jacket, exits dikhana - passengers ki taraf dekhkar.',
  't': 'technical',
  'lv': 'medium',
  'iv': True},
 {'id': 'CC17',
  'cat': 'cabin',
  'q': 'Tell me about a time you worked in a team.',
  'ref': 'Guidance: A simple story from school, college, a function or home: your role, the work, the result.',
  'tip': 'A simple story from school, college, a function or home: your role, the work, the result.',
  'hi': 'School, college, ghar ka ek example: aapka role aur natija.',
  't': 'behavioral',
  'lv': 'medium',
  'iv': True},
 {'id': 'CC18',
  'cat': 'cabin',
  'q': 'What are your strengths and weaknesses?',
  'ref': 'Guidance: Strengths: polite, patient, team player. Small real weakness plus a fix. Keep it positive.',
  'tip': 'Strengths: polite, patient, team player. Small real weakness plus a fix. Keep it positive.',
  'hi': 'Strength: vinamra, patient. Chhoti kamzori aur sudhaar.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'CC19',
  'cat': 'cabin',
  'q': 'How good is your English and Hindi? Do you know any other language?',
  'ref': 'Guidance: Be honest. List the languages. Say you will practise daily.',
  'tip': 'Be honest. List the languages. Say you will practise daily.',
  'hi': 'Bhashaon ki list sach batao. Roz practise karne ki baat karo.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC20',
  'cat': 'cabin',
  'q': 'Can you stay calm in a stressful situation? Give an example.',
  'ref': 'Guidance: A short story where you stayed calm (exam, a crowd, a family emergency). End with what you learned.',
  'tip': 'A short story where you stayed calm (exam, a crowd, a family emergency). End with what you learned.',
  'hi': 'Exam ya emergency ka chhota example, aur seekh.',
  't': 'behavioral',
  'lv': 'medium',
  'iv': True},
 {'id': 'CC21',
  'cat': 'cabin',
  'q': 'What will you do if you are not selected this time?',
  'ref': 'Guidance: Say you will ask for feedback, improve and apply again. Shows positive attitude.',
  'tip': 'Say you will ask for feedback, improve and apply again. Shows positive attitude.',
  'hi': 'Feedback loge, sudhaar karoge, phir apply karoge.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'CC22',
  'cat': 'cabin',
  'q': 'Why should we hire you?',
  'ref': 'Guidance: Three points: service attitude, calm in pressure, team player. Smile at the end.',
  'tip': 'Three points: service attitude, calm in pressure, team player. Smile at the end.',
  'hi': 'Teen baatein: service ka bhav, pressure mein shaant, team player.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'HT1',
  'cat': 'hotel',
  'q': 'Tell me about yourself in English.',
  'ref': 'Guidance: Name, studies, city, hospitality course or skill if any, why hotels. Be polite and clean in appearance.',
  'tip': 'Name, studies, city, hospitality course or skill if any, why hotels. Be polite and clean in appearance.',
  'hi': 'Naam, padhai, shehar, hospitality course/skill, hotel kyun. Vinamra raho.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'HT2',
  'cat': 'hotel',
  'q': 'Why do you want to work in the hotel industry?',
  'ref': 'Guidance: Say you enjoy serving guests and learning. A good start for a long career. Not "only for tips or free food".',
  'tip': 'Say you enjoy serving guests and learning. A good start for a long career. Not "only for tips or free food".',
  'hi': 'Guest ki seva aur seekhna pasand hai. Sirf tips/khane ke liye nahi.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True,
  'why': True},
 {'id': 'HT3',
  'cat': 'hotel',
  'q': 'What does "guest is God" (Atithi Devo Bhava) mean in a hotel?',
  'ref': 'Guidance: Guests are treated with respect and care. Greet, listen, help quickly.',
  'tip': 'Guests are treated with respect and care. Greet, listen, help quickly.',
  'hi': 'Guest ko izzat aur madad: swagat, suno, jaldi help.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'HT4',
  'cat': 'hotel',
  'q': 'What are the main departments in a hotel?',
  'ref': 'Guidance: Front office, housekeeping, food and beverage service, kitchen, maintenance, security, sales.',
  'tip': 'Front office, housekeeping, food and beverage service, kitchen, maintenance, security, sales.',
  'hi': 'Front office, housekeeping, F&B service, kitchen, maintenance, security.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'HT5',
  'cat': 'hotel',
  'q': 'What happens at guest check-in? And check-out?',
  'ref': 'Guidance: Check-in: greet, ID proof, registration, room key, tell about breakfast and Wi-Fi. Check-out: bill, collect key, thank '
         'the guest, ask for feedback.',
  'tip': 'Check-in: greet, ID proof, registration, room key, tell about breakfast and Wi-Fi. Check-out: bill, collect key, thank the '
         'guest, ask for feedback.',
  'hi': 'Check-in: swagat, ID, form, chaabi, facilities. Check-out: bill, chaabi, dhanyawad, feedback.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'HT6',
  'cat': 'hotel',
  'q': 'What is the usual check-in and check-out time?',
  'ref': 'Guidance: Many hotels use 12 or 2 PM for check-in and 11 AM or 12 noon for check-out (varies by hotel). Say you would follow the '
         'hotel policy.',
  'tip': 'Many hotels use 12 or 2 PM for check-in and 11 AM or 12 noon for check-out (varies by hotel). Say you would follow the hotel '
         'policy.',
  'hi': 'Hotel ke hisaab se badalta hai - policy follow karo.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'HT7',
  'cat': 'hotel',
  'q': 'A guest arrives early and the room is not ready. What do you do?',
  'ref': 'Guidance: Apologise, offer to keep luggage, a seat in the lobby, a welcome drink, and update them when the room is ready.',
  'tip': 'Apologise, offer to keep luggage, a seat in the lobby, a welcome drink, and update them when the room is ready.',
  'hi': 'Sorry, saaman rakhwao, lobby mein baithao, drink do, room ready hote hi batao.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT8',
  'cat': 'hotel',
  'q': 'A guest complains that the room is not clean. What will you do?',
  'ref': 'Guidance: Listen, apologise, note the room number, send housekeeping fast or change the room, follow up after.',
  'tip': 'Listen, apologise, note the room number, send housekeeping fast or change the room, follow up after.',
  'hi': 'Suno, sorry, room number note, housekeeping bhejo ya room badlo, baad mein poochho.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT9',
  'cat': 'hotel',
  'q': 'The guest says the food is cold. What will you do?',
  'ref': 'Guidance: Apologise, take the dish back, tell the kitchen, serve a fresh dish, check again with the guest.',
  'tip': 'Apologise, take the dish back, tell the kitchen, serve a fresh dish, check again with the guest.',
  'hi': 'Sorry, dish wapas, kitchen ko batao, naya serve, guest se confirm.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT10',
  'cat': 'hotel',
  'q': 'A guest asks for something that is against hotel policy. What do you say?',
  'ref': 'Guidance: Say no politely, explain the rule, offer an alternative, and ask a senior if needed.',
  'tip': 'Say no politely, explain the rule, offer an alternative, and ask a senior if needed.',
  'hi': 'Politely na, rule samjhao, alternative do, senior se poochho.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT11',
  'cat': 'hotel',
  'q': 'What is "upselling"? Give an example.',
  'ref': 'Guidance: Offering a better room, a meal combo or a service so the guest enjoys more. Example: "Would you like a sea-view room '
         'for a little extra?"',
  'tip': 'Offering a better room, a meal combo or a service so the guest enjoys more. Example: "Would you like a sea-view room for a '
         'little extra?"',
  'hi': 'Guest ko behtar room ya service suggest karna. Example: "Sea-view room lena chahenge?"',
  't': 'technical',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT12',
  'cat': 'hotel',
  'q': 'Two guests want the last available room. What will you do?',
  'ref': 'Guidance: Check booking priority, be fair and honest, offer another hotel or date if needed, tell your manager.',
  'tip': 'Check booking priority, be fair and honest, offer another hotel or date if needed, tell your manager.',
  'hi': 'Booking dekho, imaandaari se, alternative, manager ko batao.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT13',
  'cat': 'hotel',
  'q': 'How do you answer a hotel phone call?',
  'ref': 'Guidance: "Good morning, Hotel [name], [your name] speaking, how may I help you?" Smile, speak slowly, note the message.',
  'tip': '"Good morning, Hotel [name], [your name] speaking, how may I help you?" Smile, speak slowly, note the message.',
  'hi': '"Good morning, Hotel [naam], main [aapka naam], kya madad kar sakta/sakti hoon?"',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'HT14',
  'cat': 'hotel',
  'q': 'Are you comfortable with rotational shifts, night duty and festival work?',
  'ref': "Guidance: Hotels never close. Say yes if true and mention your family's support.",
  'tip': "Hotels never close. Say yes if true and mention your family's support.",
  'hi': 'Hotel 24x7 chalte hain. Shift, raat aur tyohar - sach boliye.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'HT15',
  'cat': 'hotel',
  'q': 'Can you stand for long hours? Are you comfortable with a uniform and grooming rules?',
  'ref': 'Guidance: Yes. Say you keep neat hair, clean nails, proper uniform, and good hygiene.',
  'tip': 'Yes. Say you keep neat hair, clean nails, proper uniform, and good hygiene.',
  'hi': 'Haan. Safai, uniform, grooming ka dhyan.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'HT16',
  'cat': 'hotel',
  'q': 'How do you handle guest information and security?',
  'ref': 'Guidance: Keep it private. Never share room numbers or names with strangers. Check ID.',
  'tip': 'Keep it private. Never share room numbers or names with strangers. Check ID.',
  'hi': 'Guest ki jaankari private. Kisi ko room number mat batao. ID check.',
  't': 'technical',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT17',
  'cat': 'hotel',
  'q': 'What do you do if you see something suspicious or lost property?',
  'ref': 'Guidance: Do not touch. Tell the supervisor or security. Record the place and time. Lost property goes to the lost-and-found '
         'desk.',
  'tip': 'Do not touch. Tell the supervisor or security. Record the place and time. Lost property goes to the lost-and-found desk.',
  'hi': 'Haath mat lagao, supervisor/security ko batao, jagah aur time note.',
  't': 'technical',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT18',
  'cat': 'hotel',
  'q': 'Tell me about a time you worked in a team.',
  'ref': 'Guidance: A short story from school, college, a family function or a part-time job.',
  'tip': 'A short story from school, college, a family function or a part-time job.',
  'hi': 'Chhoti kahani: aapka kaam, natija.',
  't': 'behavioral',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT19',
  'cat': 'hotel',
  'q': 'What are your strengths and weaknesses?',
  'ref': 'Guidance: Strength: polite, hard-working. A small, honest weakness and how you fix it.',
  'tip': 'Strength: polite, hard-working. A small, honest weakness and how you fix it.',
  'hi': 'Ek strength, ek chhoti kamzori aur fix.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'HT20',
  'cat': 'hotel',
  'q': 'What salary do you expect?',
  'ref': 'Guidance: As a fresher, follow hotel standards. Say you want training and growth. Ask about meals, uniform and accommodation.',
  'tip': 'As a fresher, follow hotel standards. Say you want training and growth. Ask about meals, uniform and accommodation.',
  'hi': 'Fresher ke hisaab se. Training aur growth pe zor. Meal, uniform, rehne ki jagah poochho.',
  't': 'behavioral',
  'lv': 'medium',
  'iv': True},
 {'id': 'HT21',
  'cat': 'hotel',
  'q': 'Where do you see yourself in 3 years?',
  'ref': 'Guidance: Supervisor or senior executive, after learning the work well.',
  'tip': 'Supervisor or senior executive, after learning the work well.',
  'hi': 'Supervisor ya senior executive.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'HT22',
  'cat': 'hotel',
  'q': 'Why should we hire you?',
  'ref': 'Guidance: Polite, ready to learn, ready for shifts, never late.',
  'tip': 'Polite, ready to learn, ready for shifts, never late.',
  'hi': 'Vinamra, seekhne ko tayyar, shift ke liye ready, hamesha time par.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'AP1',
  'cat': 'airport',
  'q': 'Tell me about yourself in English.',
  'ref': 'Guidance: Name, studies, city, one strength (communication, computer basics), why airport work. Neat and calm.',
  'tip': 'Name, studies, city, one strength (communication, computer basics), why airport work. Neat and calm.',
  'hi': 'Naam, padhai, shehar, ek khoobi, airport kaam kyun.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False},
 {'id': 'AP2',
  'cat': 'airport',
  'q': 'Why do you want to work as ground staff at an airport?',
  'ref': 'Guidance: Say you like working with passengers, a fast and disciplined place, learning aviation. Not "only to see planes".',
  'tip': 'Say you like working with passengers, a fast and disciplined place, learning aviation. Not "only to see planes".',
  'hi': 'Passengers se kaam, discipline, aviation seekhna - sirf plane dekhne ke liye nahi.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True,
  'why': True},
 {'id': 'AP3',
  'cat': 'airport',
  'q': 'What does ground staff do?',
  'ref': 'Guidance: Check-in, boarding pass and baggage, gate boarding, passenger help, special-assistance, announcements, flight-delay '
         'updates.',
  'tip': 'Check-in, boarding pass and baggage, gate boarding, passenger help, special-assistance, announcements, flight-delay updates.',
  'hi': 'Check-in, boarding pass, baggage, gate boarding, madad, delay ki jaankari.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'AP4',
  'cat': 'airport',
  'q': 'What is IATA? What do the codes DEL, BOM and BLR mean?',
  'ref': 'Guidance: IATA = International Air Transport Association. DEL = Delhi, BOM = Mumbai, BLR = Bengaluru.',
  'tip': 'IATA = International Air Transport Association. DEL = Delhi, BOM = Mumbai, BLR = Bengaluru.',
  'hi': 'IATA airline sangathan. DEL = Delhi, BOM = Mumbai, BLR = Bengaluru.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'AP5',
  'cat': 'airport',
  'q': 'What documents does a passenger need for a domestic flight? For an international flight?',
  'ref': 'Guidance: Domestic: valid photo ID and ticket. International: passport and visa if needed, ticket. Tell the check-in rule from '
         'your airline.',
  'tip': 'Domestic: valid photo ID and ticket. International: passport and visa if needed, ticket. Tell the check-in rule from your '
         'airline.',
  'hi': 'Domestic: ID aur ticket. International: passport, visa, ticket.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'AP6',
  'cat': 'airport',
  'q': 'What happens at check-in?',
  'ref': 'Guidance: Greet, check ID and ticket, weigh the bags, tag them, give the boarding pass with seat and gate, tell the boarding '
         'time.',
  'tip': 'Greet, check ID and ticket, weigh the bags, tag them, give the boarding pass with seat and gate, tell the boarding time.',
  'hi': 'Swagat, ID/ticket, bag weight, tag, boarding pass, time batao.',
  't': 'technical',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP7',
  'cat': 'airport',
  'q': 'What is the baggage allowance? What if a bag is overweight?',
  'ref': 'Guidance: It varies by airline and ticket. Typical domestic cabin bag is about 7 kg (varies). If the checked bag is overweight, '
         'tell the passenger the excess-baggage fee or ask them to remove items.',
  'tip': 'It varies by airline and ticket. Typical domestic cabin bag is about 7 kg (varies). If the checked bag is overweight, tell the '
         'passenger the excess-baggage fee or ask them to remove items.',
  'hi': 'Airline ke hisaab se. Overweight ho to excess fee ya saaman kam karao.',
  't': 'technical',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP8',
  'cat': 'airport',
  'q': 'What items are not allowed in a cabin bag?',
  'ref': 'Guidance: Sharp objects, lighters, flammable liquids, power banks in checked bag (rules apply), large liquids. Say "as per the '
         'security rule".',
  'tip': 'Sharp objects, lighters, flammable liquids, power banks in checked bag (rules apply), large liquids. Say "as per the security '
         'rule".',
  'hi': 'Tez cheezein, lighter, jwalansheel cheezein, bade liquid. Security rule ke hisaab se.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'AP9',
  'cat': 'airport',
  'q': 'When does check-in close and when does boarding close?',
  'ref': 'Guidance: It varies by airline and airport. Domestic check-in usually closes around 45-60 minutes before departure. Say you '
         "would follow the airline's rule.",
  'tip': 'It varies by airline and airport. Domestic check-in usually closes around 45-60 minutes before departure. Say you would follow '
         "the airline's rule.",
  'hi': 'Airline par depend. Domestic check-in aam taur par 45-60 min pehle band hota hai.',
  't': 'technical',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP10',
  'cat': 'airport',
  'q': 'A passenger arrives late after check-in closed. What will you do?',
  'ref': 'Guidance: Stay polite, explain the rule, check with the supervisor if any option exists, help them rebook.',
  'tip': 'Stay polite, explain the rule, check with the supervisor if any option exists, help them rebook.',
  'hi': 'Politely rule batao, supervisor se poochho, rebook mein madad.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP11',
  'cat': 'airport',
  'q': 'A flight is delayed by two hours and passengers are angry. What do you do?',
  'ref': 'Guidance: Announce the truth and expected time, apologise, offer water/snacks as the airline allows, update every 15-30 minutes.',
  'tip': 'Announce the truth and expected time, apologise, offer water/snacks as the airline allows, update every 15-30 minutes.',
  'hi': 'Sahi jaankari, sorry, paani/snacks (rule se), baar baar update.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP12',
  'cat': 'airport',
  'q': "A passenger's bag did not arrive. What will you do?",
  'ref': 'Guidance: Apologise, take them to the baggage service desk, fill the lost-baggage report (PIR), give the reference number.',
  'tip': 'Apologise, take them to the baggage service desk, fill the lost-baggage report (PIR), give the reference number.',
  'hi': 'Sorry, baggage desk par le jao, report bharo, reference number do.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP13',
  'cat': 'airport',
  'q': 'A passenger with a wheelchair or an elderly person needs help. What do you do?',
  'ref': 'Guidance: Ask kindly, arrange the wheelchair, tell the staff, walk with them to the gate, thank them.',
  'tip': 'Ask kindly, arrange the wheelchair, tell the staff, walk with them to the gate, thank them.',
  'hi': 'Pyaar se poochho, wheelchair arrange, gate tak saath.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP14',
  'cat': 'airport',
  'q': 'A passenger insists on a window seat that is already taken. What will you do?',
  'ref': 'Guidance: Explain, check the seat map, offer the nearest option or ask another passenger kindly, never argue.',
  'tip': 'Explain, check the seat map, offer the nearest option or ask another passenger kindly, never argue.',
  'hi': 'Samjhao, seat map dekho, nazdeeki option, bahas nahi.',
  't': 'scenario',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP15',
  'cat': 'airport',
  'q': 'You see an unattended bag at the gate. What do you do?',
  'ref': 'Guidance: Do not touch. Ask nearby people if it is theirs, move people away, inform security and your supervisor at once.',
  'tip': 'Do not touch. Ask nearby people if it is theirs, move people away, inform security and your supervisor at once.',
  'hi': 'Haath mat lagao, aas-paas poochho, security aur supervisor ko turant batao.',
  't': 'scenario',
  'lv': 'hard',
  'iv': True},
 {'id': 'AP16',
  'cat': 'airport',
  'q': 'What do you do if a passenger is on the no-fly or security-flagged list?',
  'ref': "Guidance: Do not argue. Follow the procedure and call security or the supervisor. Keep the passenger's information private.",
  'tip': "Do not argue. Follow the procedure and call security or the supervisor. Keep the passenger's information private.",
  'hi': 'Bahas nahi. Procedure, security/supervisor, jaankari private.',
  't': 'technical',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP17',
  'cat': 'airport',
  'q': 'Can you work on a computer? Do you know MS Office or any airline software?',
  'ref': 'Guidance: Say what you know (typing, Word, Excel, email). Say you will learn the booking system in training.',
  'tip': 'Say what you know (typing, Word, Excel, email). Say you will learn the booking system in training.',
  'hi': 'Jo aata hai bolo. Booking system training mein seekh loge.',
  't': 'technical',
  'lv': 'easy',
  'iv': True},
 {'id': 'AP18',
  'cat': 'airport',
  'q': 'Are you comfortable with shifts, night duty and holidays?',
  'ref': 'Guidance: Airports run 24 hours. Say yes with family support and that you will reach early.',
  'tip': 'Airports run 24 hours. Say yes with family support and that you will reach early.',
  'hi': 'Airport 24x7. Haan, ghar se support, time se pehle pahunchoge.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'AP19',
  'cat': 'airport',
  'q': 'Can you stand for long hours and wear a uniform?',
  'ref': 'Guidance: Yes. Mention good fitness, neat grooming, and a polite attitude.',
  'tip': 'Yes. Mention good fitness, neat grooming, and a polite attitude.',
  'hi': 'Haan. Fitness, saaf-suthra, vinamra.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': True},
 {'id': 'AP20',
  'cat': 'airport',
  'q': 'Tell me about a time you worked in a team or helped someone.',
  'ref': 'Guidance: A short story from school, college, an event or home: what you did and the result.',
  'tip': 'A short story from school, college, an event or home: what you did and the result.',
  'hi': 'Chhoti kahani: aapne kya kiya, natija.',
  't': 'behavioral',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP21',
  'cat': 'airport',
  'q': 'What is your salary expectation?',
  'ref': 'Guidance: As a fresher, "as per company standards". Say you want training and growth.',
  'tip': 'As a fresher, "as per company standards". Say you want training and growth.',
  'hi': 'Company standard. Training aur growth.',
  't': 'behavioral',
  'lv': 'medium',
  'iv': True},
 {'id': 'AP22',
  'cat': 'airport',
  'q': 'Why should we hire you?',
  'ref': 'Guidance: Calm in pressure, polite to passengers, learns fast, follows rules.',
  'tip': 'Calm in pressure, polite to passengers, learns fast, follows rules.',
  'hi': 'Pressure mein shaant, vinamra, jaldi seekhta/seekhti, rules follow.',
  't': 'behavioral',
  'lv': 'easy',
  'iv': False}]
